import { Language, UserSettings } from './types';

export const INITIAL_SETTINGS: UserSettings = {
  answerLength: 'Medium',
  tone: 'Simple',
  outputStyle: 'Paragraphs',
  clarifyingQuestions: true,
  documentType: 'General',
  perspective: 'Neutral',
};

export const DID_YOU_KNOW_FACTS = {
  [Language.UZ]: [
    { title: "Yangi Mehnat Kodeksi", content: "2023-yilgi Mehnat kodeksi xodimlar uchun yillik asosiy ta'tilni kamida 21 kalendar kuni etib belgiladi.", button: "Ta'til haqida" },
    { title: "O'zini o'zi band qilish", content: "O'zini o'zi band qilgan shaxslar daromad solig'idan ozod etiladi va staj uchun ixtiyoriy soliq to'lashi mumkin.", button: "Soliq imtiyozlari" },
    { title: "Aliment To'lovlari", content: "Ota-ona ishsiz bo'lsa, aliment miqdori o'rtacha oylik ish haqidan kelib chiqib hisoblanadi.", button: "Aliment tartibi" },
    { title: "Jarima Chegirmasi", content: "Ma'muriy jarimani 15 kun ichida to'lasangiz, 50% chegirmadan foydalanishingiz mumkin.", button: "Jarimalar haqida" },
    { title: "Oyna Tonirovkasi", content: "Avtomobilning orqa yon oynalarini qoraytirish (tonirovka) endi mutlaqo bepul.", button: "Tonirovka qoidalari" },
    { title: "IT Park Imtiyozlari", content: "IT Park rezidentlari daromad solig'ini atigi 7.5% miqdorida to'laydilar.", button: "IT huquqi" },
    { title: "Meros Huquqi", content: "Vafot etgan shaxsdan qolgan merosni qabul qilish uchun 6 oy ichida notariusga murojaat qilish kerak.", button: "Meros maslahati" },
    { title: "Tovar Qaytarish", content: "Iste'molchi maqbul sifatli nooziq-ovqat tovarini 10 kun ichida almashtirib olishga haqli.", button: "Iste'molchi huquqi" },
    { title: "Nikoh Yoshi", content: "O'zbekistonda erkaklar va ayollar uchun nikoh yoshi qat'iy 18 yosh etib belgilangan.", button: "Oila huquqi" },
    { title: "Propiska Tartibi", content: "Toshkent shahridan uy sotib olishda doimiy ro'yxatda turish talabi bekor qilingan.", button: "Uy-joy huquqi" },
    { title: "Qarz Tilxati", content: "850 ming so'mdan yuqori qarzlar uchun qonunan yozma shartnoma yoki tilxat tuzish shart.", button: "Qarz masalalari" },
    { title: "ID-karta", content: "Biometrik pasportni ID-kartaga almashtirish ixtiyoriy, lekin muddati tugasa majburiy.", button: "Pasport tartibi" },
    { title: "Tug'ilganlik Guvohnomasi", content: "Bola tug'ilganda guvohnomani my.gov.uz orqali uydan chiqmasdan olish mumkin.", button: "E-xizmatlar" },
    { title: "Ish haqi kechikishi", content: "Ish beruvchi ish haqini kechiktirsa, har bir kun uchun qayta moliyalash stavkasi asosida kompensatsiya to'laydi.", button: "Mehnat nizolari" },
    { title: "Shovqin Qoidalari", content: "Tungi vaqtda (23:00 dan 06:00 gacha) fuqarolarning osoyishtaligini buzish ma'muriy javobgarlikka sabab bo'ladi.", button: "Ma'muriy huquq" },
    { title: "Elektron imzo (ERI)", content: "ERI kaliti orqali barcha davlat xizmatlaridan masofadan turib foydalanish imkoniyati bor.", button: "Raqamli huquq" },
    { title: "Ta'lim krediti", content: "Xotin-qizlar uchun OTMda o'qishga foizsiz ta'lim krediti berish tizimi mavjud.", button: "Ta'lim imtiyozlari" },
    { title: "Soliq Keshbeki", content: "Xaridlardan tushgan cheklarni Soliq ilovasida skanerlab, 1% keshbek qaytarib olishingiz mumkin.", button: "Soliqlar" },
    { title: "Sudga Murojaat", content: "Iste'molchilar o'z huquqlari buzilganda sudga murojaat qilishda davlat bojidan ozod etiladilar.", button: "Sud tartibi" },
    { title: "Tadbirkorlik", content: "Yangi biznes sub'ektlari ro'yxatdan o'tgandan so'ng 3 yil davomida tekshirilmaydi.", button: "Biznes yordam" },
    { title: "Sug'urta Polis", content: "Avtomobil sug'urtasi bo'lmagan holda haydash 340 000 so'm jarimaga sabab bo'lishi mumkin.", button: "Sug'urta" },
    { title: "Uy-joy Subsidiyasi", content: "Kam ta'minlangan oilalar uy sotib olish uchun davlatdan qaytarib berilmaydigan subsidiya olishlari mumkin.", button: "Subsidiyalar" },
    { title: "Bolalar Puli", content: "Bolalar puli oilaning daromadi har bir a'zoga minimal iste'mol xarajatlaridan kam bo'lganda beriladi.", button: "Ijtimoiy yordam" },
    { title: "Tibbiy Sug'urta", content: "Sirdaryo viloyatida davlat tibbiy sug'urtasi tizimi pilot loyiha sifatida muvaffaqiyatli ishlamoqda.", button: "Sog'liqni saqlash" },
    { title: "Kadastr Pasporti", content: "Uy-joyingizning kadastr pasportini onlayn tarzda My.gov.uz orqali yangilashingiz mumkin.", button: "Kadastr" },
    { title: "Ishga Qabul", content: "Ish beruvchi ishga qabul qilishda homilador ayollarga rad javobini berishi qonunan taqiqlangan.", button: "Mehnat huquqi" },
    { title: "Jarima Foto-radar", content: "Radar orqali qayd etilgan jarima haqidagi xabar 48 soat ichida yuborilishi shart.", button: "YHQ" },
    { title: "Elektron Davlat Xizmati", content: "Bugungi kunda My.gov.uz portalida 300 dan ortiq davlat xizmatlari mavjud.", button: "E-gov" },
    { title: "Tuhmat va Haqorat", content: "Ijtimoiy tarmoqlarda tuhmat qilganlik uchun BHMning 50 baravarigacha jarima bor.", button: "Jinoyat kodeksi" },
    { title: "Haydovchilik Guvohnomasi", content: "Eski namunadagi pravolarni almashtirish muddati 2024-yilgacha uzaytirilgan edi.", button: "Hujjatlar" },
    { title: "Yaqin Qarindoshlar", content: "Sudda yaqin qarindoshlaringizga qarshi ko'rsatma bermaslik huquqingiz Konstitutsiyada mustahkamlangan.", button: "Konstitutsiya" },
    { title: "Tabiiy Gaz", content: "Gaz hisoblagichni qiyoslashdan o'tkazish xarajatlari gaz ta'minoti korxonasi tomonidan qoplanadi.", button: "Kommunal" },
    { title: "Siyosiy Partiyalar", content: "O'zbekistonda hozirda 5 ta rasmiy ro'yxatdan o'tgan siyosiy partiya faoliyat yuritadi.", button: "Siyosat" },
    { title: "Talaba Kontrakti", content: "Talaba kontrakti miqdorining 12% ini daromad solig'idan qaytarib olish mumkin.", button: "Soliq imtiyozlari" },
    { title: "Fuqarolik Berish", content: "O'zbekistonda 15 yil yashagan shaxslarga fuqarolik olish tartibi soddalashtirilgan.", button: "Migratsiya" },
    { title: "Bojxona Limiti", content: "Shaxsiy foydalanish uchun pochtadan keladigan tovarlarning bojsiz limiti 100 dollarni tashkil etadi.", button: "Bojxona" },
    { title: "Iste'molchi va Chek", content: "Chek bermagan sotuvchi ustidan Soliq ilovasi orqali xabar berish huquqingiz bor.", button: "Iste'molchi" },
    { title: "Avtorlik Huquqi", content: "Asar yaratilgan paytdan boshlab unga nisbatan mualliflik huquqi paydo bo'ladi.", button: "Intellektual mulk" },
    { title: "Dori-darmon Narxi", content: "Dorixonalarda dori vositalarining ustama narxi 20% dan oshishi mumkin emas.", button: "Sog'liqni saqlash" },
    { title: "Nogironlik Imtiyozi", content: "I va II guruh nogironligi bor shaxslar ko'plab davlat bojlaridan ozod qilingan.", button: "Imtiyozlar" },
    { title: "Xususiy Tadbirkor", content: "Yakka tartibdagi tadbirkorlar 5 nafargacha xodimni yollash huquqiga ega.", button: "Tadbirkorlik" },
    { title: "MCHJ Ustavi", content: "MCHJ ustav fondining minimal miqdori hozirda qonun bilan chegaralanmagan.", button: "Biznes" },
    { title: "Sud Buyrug'i", content: "Qarzni undirish bo'yicha sud buyrug'i sud majlisi o'tkazilmasdan chiqariladi.", button: "Sud tizimi" },
    { title: "Notarius", content: "Notarial harakatlar uchun to'lanadigan davlat boji stavkalari barcha hududlarda bir xil.", button: "Notarius" },
    { title: "Propiska va Ish", content: "Ishga qabul qilishda Toshkent propiskasi yo'qligi sababli rad etish qonunga xilofdir.", button: "Inson huquqlari" },
    { title: "Iste'molchi va Kafolat", content: "Kafolat muddati ko'rsatilmagan tovarlar uchun kafolat muddati 6 oy deb hisoblanadi.", button: "Iste'molchi" },
    { title: "Tug'ruq Nafaqasi", content: "Xususiy sektorda ishlovchi ayollarga homiladorlik nafaqasi ijtimoiy sug'urta jamg'armasidan to'lanadi.", button: "Ijtimoiy himoya" },
    { title: "Elektron Savdo", content: "Internet-do'konlar ham iste'molchilar huquqlarini himoya qilish qonuniga bo'ysunadi.", button: "Savdo" },
    { title: "Arenda Shartnomasi", content: "Ijara shartnomasi 1 yildan ortiq bo'lsa, notarial tasdiqlanishi majburiy (jismoniy shaxslar uchun ixtiyoriy).", button: "Ijara" },
    { title: "Yer Huquqi", content: "O'zbekistonda qishloq xo'jaligiga mo'ljallanmagan yerlarni xususiylashtirish imkoniyati mavjud.", button: "Yer kodeksi" },
    { title: "Advokatlik Siri", content: "Advokat va uning mijozi o'rtasidagi suhbat sirdir va dalil sifatida ishlatilmaydi.", button: "Advokatura" },
    { title: "Ayollar Daftari", content: "Ijtimoiy yordamga muhtoj ayollar 'Ayollar daftari' orqali moddiy ko'mak olishlari mumkin.", button: "Yordam" },
    { title: "Bog'cha Navbati", content: "Bola 3 yoshga to'lgach davlat bog'chasiga onlayn navbat asosida qabul qilinadi.", button: "Ta'lim" },
    { title: "Eksport Imtiyozi", content: "Eksport qiluvchi korxonalar foyda solig'idan sezilarli chegirmalarga ega bo'ladilar.", button: "Eksport" },
    { title: "Xorijda Ishlash", content: "Chet elda ishlovchilar ixtiyoriy ravishda ijtimoiy soliq to'lab, staj hisoblashlari mumkin.", button: "Migratsiya" },
    { title: "Jarima To'lamaslik", content: "Ma'muriy jarima 60 kun ichida to'lanmasa, MIB tomonidan majburiy undiriladi.", button: "MIB" },
    { title: "Bolalar Ombudsmani", content: "O'zbekistonda bolalar huquqlarini himoya qiluvchi alohida Ombudsman faoliyat yuritadi.", button: "Bolalar huquqi" },
    { title: "Reklama Qoidalari", content: "Telekanallarda dori vositalari reklamasi uchun qat'iy cheklovlar mavjud.", button: "Reklama" },
    { title: "Ipoteka Kredit", content: "Yosh oilalar uchun ipoteka krediti bo'yicha subsidiya to'lab beriladi.", button: "Ipoteka" },
    { title: "Ekologik Nazorat", content: "Daraxtlarni noqonuniy kesganlik uchun jismoniy shaxslarga katta jarimalar belgilangan.", button: "Ekologiya" },
    { title: "Soliq Deklaratsiyasi", content: "Shaxslar qo'shimcha daromadlari bo'yicha yiliga bir marta deklaratsiya topshirishlari shart.", button: "Soliqlar" },
    { title: "Tibbiy Ma'lumot", content: "Bemor o'z kasallik tarixi va tahlil natijalarini olishga to'liq huquqli.", button: "Bemor huquqi" },
    { title: "Yuridik Shaxs", content: "Tadbirkorlik sub'ektini ro'yxatdan o'tkazish bor-yo'g'i 30 daqiqa vaqt oladi.", button: "Ro'yxatdan o'tish" },
    { title: "Gaz Balon", content: "Avtomobildagi gaz ballonini har 3 yilda texnik sinovdan o'tkazish majburiydir.", button: "Xavfsizlik" },
    { title: "Vasiylik", content: "Vasiylik va homiylik organlari tuman xalq ta'limi bo'limlari qoshida faoliyat yuritadi.", button: "Oila" },
    { title: "Sud Majlisi", content: "Ochiq sud majlislarida har qanday fuqaro ishtirok etish va kuzatish huquqiga ega.", button: "Sud" },
    { title: "Pochta Xizmati", content: "Pochta orqali yuborilgan jo'natmaning yo'qolishi uchun aloqa operatori javobgar.", button: "Aloqa" },
    { title: "Haj va Umra", content: "Haj va umra ziyoratlarini tashkil etish faqat litsenziyaga ega tashkilotlar tomonidan amalga oshiriladi.", button: "Din" },
    { title: "Fuqarolik Sudlari", content: "Fuqarolik sudlarida ish ko'rish muddati odatda 1 oydan 2 oygacha davom etadi.", button: "Protsess" },
    { title: "Yozma Shartnoma", content: "Shartnomani elektron raqamli imzo orqali masofadan imzolash qonuniy kuchga ega.", button: "Raqamli huquq" },
    { title: "Maishiy Texnika", content: "Nosoz maishiy texnikani 3 martadan ko'p ta'mirlashga to'g'ri kelsa, uni almashtirishni talab qiling.", button: "Iste'molchi" },
    { title: "Kredit Tarixi", content: "Har bir fuqaro yiliga bir marta o'z kredit tarixini bepul olishga haqli.", button: "Kredit" },
    { title: "Soliq Imtiyozi", content: "Farzandini xususiy bog'chaga bergan ota-onalarga soliq imtiyozlari mavjud.", button: "Soliq" },
    { title: "O'rindoshlik", content: "Xodim asosiy ishidan bo'sh vaqtida boshqa joyda o'rindoshlik asosida ishlashi mumkin.", button: "Mehnat" },
    { title: "Ijtimoiy Tarmoq", content: "Ijtimoiy tarmoqda shaxsiy ma'lumotlarni ruxsatsiz tarqatish qonun bilan taqiqlanadi.", button: "Kiber-xavfsizlik" },
    { title: "Ta'lim Sifati", content: "Nodavlat ta'lim muassasalari ham davlat namunasidagi diplom berish huquqiga ega.", button: "Ta'lim" },
    { title: "Kichik Biznes", content: "Kichik biznes sub'ektlari uchun soddalashtirilgan soliq tizimi amal qiladi.", button: "Biznes" },
    { title: "Valyuta Ayirboshlash", content: "Ko'chada valyuta ayirboshlash ma'muriy va jinoiy javobgarlikka sabab bo'ladi.", button: "Valyuta" },
    { title: "Merosxo'rlar", content: "Vasiyatnoma bo'lmaganda meros qonun bo'yicha navbatdagi merosxo'rlarga o'tadi.", button: "Meros" },
    { title: "Amnistiya", content: "Amnistiya akti faqat O'zbekiston Respublikasi Senati tomonidan qabul qilinadi.", button: "Huquq" }
  ],
  [Language.RU]: [
    { title: "Новый Трудовой Кодекс", content: "Трудовой кодекс 2023 года установил минимальный ежегодный отпуск в 21 календарный день.", button: "Об отпуске" },
    { title: "Самозанятость", content: "Самозанятые лица освобождаются от подоходного налога и платят соцналог добровольно.", button: "Налоги" },
    { title: "Алименты", content: "Если родитель безработный, алименты рассчитываются исходя из средней зарплаты по стране.", button: "Алименты" },
    { title: "Скидка на штрафы", content: "При оплате административного штрафа в течение 15 дней действует скидка 50%.", button: "Штрафы" },
    { title: "Тонировка стекол", content: "Тонировка задних боковых стекол автомобиля теперь абсолютно бесплатна.", button: "ПДД" },
    { title: "Льготы IT Park", content: "Резиденты IT Park платят подоходный налог по ставке всего 7.5%.", button: "IT право" },
    { title: "Наследование", content: "Для принятия наследства необходимо обратиться к нотариусу в течение 6 месяцев.", button: "Наследство" },
    { title: "Возврат товара", content: "Потребитель имеет право обменять непродовольственный товар в течение 10 дней.", button: "Права потребителей" },
    { title: "Брачный возраст", content: "В Узбекистане брачный возраст для мужчин и женщин установлен на уровне 18 лет.", button: "Семейное право" },
    { title: "Прописка", content: "Требование наличия прописки для покупки жилья в Ташкенте полностью отменено.", button: "Жилье" },
    { title: "Долговая расписка", content: "Для займов свыше 850 тысяч сумов закон требует наличие письменной расписки.", button: "Займы" },
    { title: "ID-карты", content: "Замена паспорта на ID-карту является добровольной до истечения срока действия паспорта.", button: "Документы" },
    { title: "Свидетельство о рождении", content: "Получить свидетельство о рождении можно онлайн через портал my.gov.uz.", button: "Э-услуги" },
    { title: "Задержка зарплаты", content: "Работодатель обязан выплатить компенсацию за каждый день задержки заработной платы.", button: "Трудовые споры" },
    { title: "Правила тишины", content: "Нарушение покоя граждан в ночное время (с 23:00 до 06:00) влечет штраф.", button: "Админ. право" },
    { title: "ЭЦП ключ", content: "Электронная подпись дает доступ ко всем госуслугам из любой точки мира.", button: "Цифровое право" },
    { title: "Образовательный кредит", content: "Для женщин предусмотрены беспроцентные кредиты на обучение в вузах.", button: "Образование" },
    { title: "Налоговый кэшбэк", content: "Сканируйте чеки в приложении Soliq и получайте кэшбэк 1% от суммы покупки.", button: "Налоги" },
    { title: "Обращение в суд", content: "Потребители освобождаются от госпошлины при подаче исков о защите прав.", button: "Суд" },
    { title: "Проверки бизнеса", content: "Новые субъекты предпринимательства не проверяются в течение первых 3 лет.", button: "Для бизнеса" },
    { title: "Страховой полис", content: "Вождение без страховки может привести к штрафу в размере 340 000 сумов.", button: "Страхование" },
    { title: "Субсидия на жилье", content: "Малообеспеченные семьи могут получить безвозмездную субсидию на покупку жилья.", button: "Жилье" },
    { title: "Детские пособия", content: "Пособия выплачиваются, если доход на каждого члена семьи ниже МРОТ.", button: "Соцзащита" },
    { title: "Медстрахование", content: "В Сырдарьинской области успешно работает пилотная система госмедстрахования.", button: "Здоровье" },
    { title: "Кадастровый паспорт", content: "Обновить кадастровый паспорт можно онлайн через My.gov.uz.", button: "Недвижимость" },
    { title: "Прием на работу", content: "Работодателям запрещено отказывать в приеме на работу беременным женщинам.", button: "Работа" },
    { title: "Штрафы с камер", content: "Сообщение о штрафе с камеры должно быть отправлено в течение 48 часов.", button: "Авто" },
    { title: "Госуслуги онлайн", content: "На портале My.gov.uz доступно уже более 300 различных госуслуг.", button: "Госуслуги" },
    { title: "Клевета и оскорбления", content: "За клевету в соцсетях предусмотрены штрафы до 50 БРВ.", button: "УК РУз" },
    { title: "Водительские права", content: "Срок замены старых прав был продлен до конца 2023 года.", button: "Права" },
    { title: "Близкие родственники", content: "Право не свидетельствовать против близких закреплено в Конституции.", button: "Право" },
    { title: "Природный газ", content: "Расходы на поверку газовых счетчиков несет газоснабжающая организация.", button: "ЖКХ" },
    { title: "Политические партии", content: "В Узбекистане официально зарегистрировано и действует 5 политических партий.", button: "Политика" },
    { title: "Налог на обучение", content: "Можно вернуть 12% подоходного налога от суммы оплаты за обучение.", button: "Льготы" },
    { title: "Гражданство РУз", content: "Упрощен порядок получения гражданства для лиц, живущих в стране 15 лет.", button: "Паспорт" },
    { title: "Таможенный лимит", content: "Беспошлинный лимит на посылки из-за границы составляет 100 долларов.", button: "Таможня" },
    { title: "Чеки в магазинах", content: "Вы имеете право жаловаться через ГНК, если вам не выдали чек.", button: "Потребитель" },
    { title: "Авторское право", content: "Авторское право возникает в момент создания произведения автоматически.", button: "Интеллект. собственность" },
    { title: "Цены на лекарства", content: "Торговая надбавка на лекарства в аптеках не может превышать 20%.", button: "Медицина" },
    { title: "Льготы инвалидам", content: "Инвалиды I и II групп освобождены от многих видов госпошлин.", button: "Льготы" },
    { title: "Частный бизнес", content: "Индивидуальные предприниматели могут нанимать до 5 сотрудников.", button: "Бизнес" },
    { title: "Устав ООО", content: "Минимальный размер уставного фонда ООО больше не ограничен законом.", button: "Юрлица" },
    { title: "Судебный приказ", content: "Приказ о взыскании долга выносится без проведения судебного заседания.", button: "Судопроизводство" },
    { title: "Нотариат", content: "Ставки госпошлин за нотариальные действия едины по всей республике.", button: "Нотариус" },
    { title: "Прописка и работа", content: "Отказ в приеме на работу из-за отсутствия прописки незаконен.", button: "Права человека" },
    { title: "Гарантия товара", content: "Если срок гарантии не указан, он считается равным 6 месяцам.", button: "Гарантия" },
    { title: "Декретные выплаты", content: "Пособия по беременности для частного сектора платит Соцстрах.", button: "Соцзащита" },
    { title: "Онлайн торговля", content: "Интернет-магазины обязаны соблюдать закон о правах потребителей.", button: "E-commerce" },
    { title: "Договор аренды", content: "Договоры аренды жилья подлежат обязательной регистрации в ГНК.", button: "Аренда" },
    { title: "Приватизация земли", content: "В РУз разрешена приватизация земель несельскохозяйственного назначения.", button: "Земля" },
    { title: "Адвокатская тайна", content: "Разговоры адвоката с клиентом конфиденциальны и не являются уликой.", button: "Адвокат" },
    { title: "Женская тетрадь", content: "Нуждающиеся женщины могут получить помощь через систему 'Аёллар дафтари'.", button: "Помощь" },
    { title: "Очередь в сад", content: "Запись в детский сад с 3 лет осуществляется онлайн через my.gov.uz.", button: "Образование" },
    { title: "Экспортные льготы", content: "Экспортеры имеют право на значительные скидки по налогу на прибыль.", button: "Экспорт" },
    { title: "Работа за границей", content: "Трудовые мигранты могут добровольно платить соцналог для стажа.", button: "Миграция" },
    { title: "Неуплата штрафов", content: "Штрафы, не оплаченные за 60 дней, взыскиваются принудительно через БПИ.", button: "БПИ" },
    { title: "Детский Омбудсман", content: "В Узбекистане действует отдельный институт по защите прав детей.", button: "Дети" },
    { title: "Реклама лекарств", content: "Реклама лекарственных средств на ТВ имеет строгие ограничения.", button: "Реклама" },
    { title: "Ипотека молодым", content: "Молодым семьям предоставляются субсидии на оплату ипотеки.", button: "Ипотека" },
    { title: "Вырубка деревьев", content: "За незаконную вырубку деревьев установлены крупные штрафы.", button: "Экология" },
    { title: "Декларация доходов", content: "Граждане обязаны раз в год подавать декларацию о доп. доходах.", button: "Налоги" },
    { title: "Мед. информация", content: "Пациент имеет право знать свой диагноз и видеть историю болезни.", button: "Пациент" },
    { title: "Регистрация бизнеса", content: "Регистрация ИП или ООО занимает всего около 30 минут онлайн.", button: "Регистрация" },
    { title: "ГБО на авто", content: "Проверка газовых баллонов на авто обязательна каждые 3 года.", button: "Безопасность" },
    { title: "Опекунство", content: "Органы опеки работают при районных отделах образования.", button: "Семья" },
    { title: "Открытость судов", content: "Любой гражданин может присутствовать на открытых судебных процессах.", button: "Суд" },
    { title: "Почта и посылки", content: "За сохранность посылки несет ответственность оператор связи.", button: "Почта" },
    { title: "Хадж и Умра", content: "Организация паломничества разрешена только лицензированным фирмам.", button: "Паломничество" },
    { title: "Сроки в судах", content: "Рассмотрение гражданских дел обычно занимает от 1 до 2 месяцев.", button: "Процесс" },
    { title: "Электронная подпись", content: "Документы, подписанные ЭЦП, имеют такую же силу, как бумажные.", button: "Документы" },
    { title: "Ремонт техники", content: "Если технику чинили более 3 раз за срок гарантии, требуйте замены.", button: "Потребитель" },
    { title: "Кредитная история", content: "Каждый гражданин имеет право на один бесплатный отчет в год.", button: "Кредит" },
    { title: "Частные сады", content: "При оплате частного сада родителям положен налоговый вычет.", button: "Налоги" },
    { title: "Совместительство", content: "Работник может работать по совместительству в свободное от основной работы время.", button: "Работа" },
    { title: "Персональные данные", content: "Разглашение личных данных без согласия запрещено законом.", button: "Закон" },
    { title: "Дипломы частных вузов", content: "Дипломы лицензированных частных вузов признаются государством.", button: "Образование" },
    { title: "Налог с оборота", content: "Для малого бизнеса действует упрощенная система налога с оборота.", button: "Бизнес" },
    { title: "Обмен валюты", content: "Обмен валюты 'с рук' влечет административную ответственность.", button: "Валюта" },
    { title: "Наследники", content: "При отсутствии завещания наследство делится по закону в порядке очереди.", button: "Наследство" },
    { title: "Сенат и амнистия", content: "Только Сенат Олий Мажлиса имеет право принимать акты амнистии.", button: "Право" }
  ],
  [Language.EN]: [
    { title: "New Labor Code", content: "The 2023 Labor Code set the minimum annual leave for employees at 21 calendar days.", button: "About Leave" },
    { title: "Self-Employment", content: "Self-employed individuals are exempt from income tax and can pay social tax voluntarily.", button: "Tax Benefits" },
    { title: "Alimony Payments", content: "If a parent is unemployed, alimony is calculated based on the average national monthly salary.", button: "Alimony" },
    { title: "Fine Discount", content: "A 50% discount applies if you pay an administrative fine within 15 days.", button: "Fines" },
    { title: "Window Tinting", content: "Tinting for the rear side windows of cars is now completely free of charge.", button: "Traffic Rules" },
    { title: "IT Park Benefits", content: "IT Park residents pay a reduced income tax rate of only 7.5%.", button: "IT Law" },
    { title: "Inheritance Law", content: "You must apply to a notary within 6 months to claim an inheritance after a death.", button: "Inheritance" },
    { title: "Product Returns", content: "Consumers can exchange non-food items of proper quality within 10 days of purchase.", button: "Consumer Rights" },
    { title: "Marriage Age", content: "The legal marriage age in Uzbekistan is strictly set at 18 for both men and women.", button: "Family Law" },
    { title: "Residency Rules", content: "The permanent residency requirement for buying property in Tashkent has been abolished.", button: "Housing Law" },
    { title: "Debt Receipts", content: "Loans exceeding 850,000 UZS legally require a written agreement or receipt.", button: "Debt Issues" },
    { title: "ID-Cards", content: "Replacing a biometric passport with an ID-card is voluntary until the passport expires.", button: "Passports" },
    { title: "Birth Certificates", content: "You can obtain birth certificates online via the my.gov.uz portal.", button: "E-Services" },
    { title: "Salary Delays", content: "Employers must pay daily compensation for any delays in salary payments.", button: "Labor Disputes" },
    { title: "Noise Regulations", content: "Disturbing public peace during night hours (23:00 to 06:00) leads to fines.", button: "Admin Law" },
    { title: "Digital Signature (ERI)", content: "ERI keys allow remote access to all government digital services.", button: "Digital Rights" },
    { title: "Education Loans", content: "Interest-free education loans are available specifically for women in higher education.", button: "Education" },
    { title: "Tax Cashback", content: "Scan receipts in the Soliq app to get a 1% cashback on your purchases.", button: "Taxes" },
    { title: "Access to Justice", content: "Consumers are exempt from court fees when filing for consumer rights protection.", button: "Court Order" },
    { title: "Business Protection", content: "New businesses are protected from inspections for the first 3 years of operation.", button: "Business Support" },
    { title: "Insurance Policy", content: "Driving without valid car insurance can lead to a fine of 340,000 UZS.", button: "Insurance" },
    { title: "Housing Subsidy", content: "Low-income families may receive a non-repayable government subsidy for home purchases.", button: "Housing" },
    { title: "Child Welfare", content: "Child benefits are provided if the family income per member is below the living minimum.", button: "Social Care" },
    { title: "Medical Insurance", content: "A pilot project for state medical insurance is currently active in the Syrdarya region.", button: "Health" },
    { title: "Property Cadastre", content: "You can update your property's cadastral passport online via the My.gov.uz portal.", button: "Property" },
    { title: "Equal Employment", content: "It is legally forbidden for employers to refuse hiring women due to pregnancy.", button: "Employment" },
    { title: "Camera Fines", content: "Traffic fine notices from cameras must be sent to the owner within 48 hours.", button: "Traffic" },
    { title: "Gov Services", content: "The My.gov.uz portal now offers over 300 different digital government services.", button: "E-gov" },
    { title: "Libel Penalties", content: "Defamation on social media can result in fines up to 50 times the base calculated value.", button: "Criminal Law" },
    { title: "Driving Licenses", content: "The deadline for renewing old-style driving licenses has been extended multiple times.", button: "Licenses" },
    { title: "Right to Silence", content: "The right not to testify against close relatives is guaranteed by the Constitution.", button: "Constitutional" },
    { title: "Utility Costs", content: "The cost of testing gas meters is covered by the gas supply organization, not the consumer.", button: "Utilities" },
    { title: "Political Parties", content: "There are currently 5 officially registered political parties in Uzbekistan.", button: "Politics" },
    { title: "Education Rebate", content: "You can claim a 12% income tax refund on university tuition fee payments.", button: "Tax Refund" },
    { title: "Citizenship Rules", content: "The procedure for obtaining citizenship is simplified for those residing for 15 years.", button: "Immigration" },
    { title: "Customs Duty", content: "The duty-free limit for international mail parcels for personal use is 100 USD.", button: "Customs" },
    { title: "Store Receipts", content: "You have the right to report a seller via the Tax app if they refuse to issue a receipt.", button: "Consumer" },
    { title: "Copyright Law", content: "Copyright protection applies automatically from the moment a work is created.", button: "IP Law" },
    { title: "Pharmacy Prices", content: "Trade markups on essential medicines in pharmacies cannot exceed 20%.", button: "Healthcare" },
    { title: "Disability Benefits", content: "Persons with Group I and II disabilities are exempt from many state fees.", button: "Benefits" },
    { title: "Entrepreneurship", content: "Individual Entrepreneurs (IE) are allowed to hire up to 5 employees.", button: "Small Business" },
    { title: "LLC Capital", content: "There is no longer a minimum charter capital requirement for forming an LLC.", button: "Corporate" },
    { title: "Court Order", content: "A court order for debt collection can be issued without a full hearing in many cases.", button: "Litigation" },
    { title: "Notary Fees", content: "State fees for notarial services are standardized across the entire country.", button: "Notary" },
    { title: "Registration Bias", content: "Refusing employment due to lack of a Tashkent residency (Propiska) is illegal.", button: "Human Rights" },
    { title: "Product Warranty", content: "If no warranty is specified, a statutory period of 6 months typically applies.", button: "Warranty" },
    { title: "Maternity Fund", content: "Maternity benefits for private-sector employees are paid by the Social Insurance Fund.", button: "Social Care" },
    { title: "Online Sales", content: "E-commerce shops must strictly follow the Law on Protection of Consumer Rights.", button: "E-commerce" },
    { title: "Rental Registration", content: "Rental agreements for residential property must be registered with the tax authorities.", button: "Rental" },
    { title: "Land Ownership", content: "Uzbekistan allows the privatization of non-agricultural land by individuals and legal entities.", button: "Land Law" },
    { title: "Client Privacy", content: "Attorney-client communication is confidential and cannot be used as evidence.", button: "Legal Profession" },
    { title: "Women's Registry", content: "Women in need can access financial and social aid via the 'Ayollar Daftari' system.", button: "Support" },
    { title: "Preschool Enrollment", content: "Online enrollment for state kindergartens starts when a child reaches age 3.", button: "Education" },
    { title: "Export Perks", content: "Companies that export goods/services qualify for significant corporate tax reductions.", button: "Export" },
    { title: "Migrant Pensions", content: "Labor migrants can pay voluntary social tax to count their time abroad for retirement.", button: "Pensions" },
    { title: "Unpaid Fines", content: "Administrative fines unpaid for 60 days are forcibly collected by the MIB.", button: "Enforcement" },
    { title: "Children's Ombudsman", content: "A dedicated Ombudsman institution protects the rights of children in Uzbekistan.", button: "Children" },
    { title: "Medicine Ads", content: "Advertising pharmaceutical products on TV is subject to strict legal regulations.", button: "Advertising" },
    { title: "Mortgage Help", content: "Young families can apply for subsidies to help cover mortgage interest payments.", button: "Mortgage" },
    { title: "Tree Protection", content: "Heavy fines are imposed for the illegal cutting of trees in urban areas.", button: "Environment" },
    { title: "Income Tax", content: "Individuals are required to submit an annual tax declaration for additional income.", button: "Taxation" },
    { title: "Medical Rights", content: "Every patient has the right to access their full medical history and lab results.", button: "Patient" },
    { title: "Quick Registration", content: "Registering a new business as an IE or LLC takes only about 30 minutes online.", button: "Business" },
    { title: "LPG Safety", content: "Technical inspection of LPG cylinders in cars is mandatory every 3 years.", button: "Safety" },
    { title: "Guardianship", content: "Guardianship authorities operate under regional departments of public education.", button: "Family" },
    { title: "Public Hearings", content: "Any citizen has the right to attend and observe open court hearings.", button: "Courts" },
    { title: "Postal Liability", content: "The postal operator is liable for the loss or damage of a registered shipment.", button: "Postal" },
    { title: "Religious Travel", content: "Organizing Hajj and Umrah pilgrimages is restricted to licensed organizations.", button: "Travel" },
    { title: "Trial Durations", content: "Civil case trials in Uzbekistan usually conclude within 1 to 2 months.", button: "Procedure" },
    { title: "Digital Docs", content: "Documents signed with an ERI key have the same legal weight as paper ones.", button: "Digital" },
    { title: "Tech Replacement", content: "If a major appliance is repaired 3+ times under warranty, you can demand replacement.", button: "Consumer" },
    { title: "Credit Score", content: "Every citizen is entitled to one free credit history report per calendar year.", button: "Credit" },
    { title: "Preschool Tax", content: "Income tax deductions are available for parents paying for private kindergartens.", button: "Tax" },
    { title: "Dual Employment", content: "An employee can hold a secondary job during their off-hours from primary work.", button: "Work" },
    { title: "Data Privacy", content: "Distributing someone's personal data without their consent is a legal offense.", button: "Privacy" },
    { title: "Private Degree", content: "Diplomas from licensed private universities are officially recognized by the state.", button: "Education" },
    { title: "Small Biz Tax", content: "Small businesses can choose a simplified turnover tax system for easier accounting.", button: "Business" },
    { title: "Currency Trade", content: "Exchanging foreign currency in unauthorized street markets is a punishable offense.", button: "Finance" },
    { title: "Inheritance Order", content: "If no will exists, inheritance is distributed to heirs in a statutory order of priority.", button: "Inheritance" },
    { title: "Senate Amnesty", content: "The Senate of Oliy Majlis holds the exclusive power to pass acts of amnesty.", button: "Amnesty" }
  ]
};

export const TOPICS_DATA = {
  [Language.UZ]: [
    {
      category: "Oila Huquqi",
      items: [
        { title: "Ajrashish tartibi", prompt: "Ajrashish tartibi qanday? Sudga qanday hujjatlar kerak?" },
        { title: "Aliment undirish", prompt: "Aliment undirish uchun nima qilish kerak? Miqdori qancha?" },
        { title: "Nikoh shartnomasi", prompt: "Nikoh shartnomasi qanday tuziladi va u nimalarni o'z ichiga oladi?" },
        { title: "Vasiylik va homiylik", prompt: "Bolaga vasiylikni rasmiylashtirish tartibi qanday?" },
        { title: "Oilaviy zo'ravonlik", prompt: "Oilaviy zo'ravonlik bo'lganda himoya orderini qanday olish mumkin?" },
        { title: "Mulkni bo'lish", prompt: "Ajrashish paytida birgalikdagi mulk qanday taqsimlanadi?" }
      ]
    },
    {
      category: "Mehnat Huquqi",
      items: [
        { title: "Mehnat ta'tili", prompt: "Yillik mehnat ta'tili necha kun bo'lishi kerak va qanday hisoblanadi?" },
        { title: "Ishdan bo'shatish", prompt: "Xodimni ishdan bo'shatishning qonuniy asoslari qanday?" },
        { title: "Ish haqi kechikishi", prompt: "Ish haqi kechiktirilsa nima qilish kerak? Qanday javobgarlik bor?" },
        { title: "Dekret ta'tili", prompt: "Homiladorlik va tug'ish ta'tili pullari kim tomonidan to'lanadi?" },
        { title: "Sinov muddati", prompt: "Ishga kirishda sinov muddati qoidalari va muddati qanday?" },
        { title: "Mehnat shartnomasi", prompt: "Yangi Mehnat kodeksi bo'yicha shartnoma tuzish qoidalari." }
      ]
    },
    {
      category: "Mulk va Uy-joy",
      items: [
        { title: "Uy-joy oldi-sotdisi", prompt: "Uy sotib olishda notarius qanday hujjatlarni talab qiladi?" },
        { title: "Ijara shartnomasi", prompt: "Ijara shartnomasini soliq organida ro'yxatdan o'tkazish majburiymi?" },
        { title: "Merosni rasmiylashtirish", prompt: "Merosga egalik qilish huquqi qachon va qanday paydo bo'ladi?" },
        { title: "Snos (Buzilish)", prompt: "Uy buzilishga tushganda kompensatsiya qanday to'lanadi?" },
        { title: "Propiska tartibi", prompt: "Toshkent shahrida doimiy ro'yxatga turishning yangi tartibi qanday?" },
        { title: "Kadastr hujjati", prompt: "Kadastr hujjatini yo'qotib qo'ysa yoki yangilasa nima qilish kerak?" }
      ]
    },
    {
      category: "Avtomobil va YHQ",
      items: [
        { title: "Jarima to'lash", prompt: "Jarimani onlayn to'lash va chegirmadan foydalanishingiz mumkin?" },
        { title: "Oyna tonirovkasi", prompt: "Avtomobil oynalarini qoraytirish narxlari va ruxsatnoma olish." },
        { title: "YTH (Avariya)", prompt: "YTH sodir bo'lganda sug'urta to'lovini olish tartibi qanday?" },
        { title: "Ishonchnoma", prompt: "Avtomobil boshqarish uchun ishonchnoma (doverennost) turlari." },
        { title: "Gaz baloni", prompt: "Avtomobilga gaz baloni o'rnatish uchun ruxsatnoma kerakmi?" },
        { title: "Mast holda haydash", prompt: "Mast holda mashina haydash uchun qanday jazolar bor?" }
      ]
    },
    {
      category: "Bank va Moliya",
      items: [
        { title: "Kredit tarixi", prompt: "Kredit tarixini qanday tekshirish va to'g'irlash mumkin?" },
        { title: "Ipoteka krediti", prompt: "Yosh oilalar uchun ipoteka krediti shartlari qanday?" },
        { title: "Plastik karta firibgarligi", prompt: "Plastik kartadan pul o'g'irlanganda bank javobgarmi?" },
        { title: "Mikroqarz", prompt: "Mikroqarz olish uchun qanday hujjatlar kerak?" },
        { title: "Omonat turlari", prompt: "Bankdagi omonatlar davlat tomonidan kafolatlanadimi?" },
        { title: "Qarz qaytarish", prompt: "Bankdan olingan qarzni to'lay olmaslik oqibatlari qanday?" }
      ]
    },
    {
      category: "Migratsiya va Viza",
      items: [
        { title: "Zagran pasport", prompt: "Xorijga chiqish pasportini olish tartibi va muddati qanday?" },
        { title: "Chet elda ishlash", prompt: "Tashqi mehnat migratsiyasi agentligi orqali ketish tartibi." },
        { title: "Fuqarolik olish", prompt: "O'zbekiston fuqaroligini olishning osonlashtirilgan tartibi." },
        { title: "Deportatsiya", prompt: "Deportatsiya qilinganligini va muddatini qanday tekshirish mumkin?" },
        { title: "Vaqtincha ro'yxatdan o'tish", prompt: "Chet ellik fuqarolarni ro'yxatga qo'yish qoidalari." },
        { title: "Ishchi viza", prompt: "Chet elliklarga O'zbekistonda ishlash uchun ruxsatnoma olish." }
      ]
    },
    {
      category: "Tadbirkorlik",
      items: [
        { title: "YATT ochish", prompt: "Yakka tartibdagi tadbirkor sifatida ro'yxatdan o'tish va soliqlar." },
        { title: "MCHJ tashkil etish", prompt: "MCHJ ochish uchun ustav fondi va hujjatlar ro'yxati." },
        { title: "Litsenziya olish", prompt: "Qaysi faoliyat turlari uchun litsenziya talab qilinadi?" },
        { title: "Davlat subsidiyalari", prompt: "Tadbirkorlar uchun davlat tomonidan qanday subsidiyalar bor?" },
        { title: "Eksport va Import", prompt: "Mahsulotni exports qilish uchun qanday bojxona hujjatlari kerak?" },
        { title: "Franshiza", prompt: "Franshiza shartnomasi tuzishning huquqiy asoslari." }
      ]
    },
    {
      category: "Sog'liqni Saqlash",
      items: [
        { title: "Nogironlik guruhi", prompt: "Nogironlik guruhini belgilash tartibi va imtiyozlar." },
        { title: "Bepul dori-darmon", prompt: "Qaysi kasalliklar uchun bepul dori berilishi shart?" },
        { title: "Order olish", prompt: "Ixtisoslashtirilgan shifoxonalarga bepul davolanish uchun order olish." },
        { title: "Xususiy klinikada", prompt: "Xususiy klinikada noto'g'ri davolansa kimga shikoyat qilish kerak?" },
        { title: "Majburiy sug'urta", prompt: "Tibbiy sug'urta tizimi qachondan ishga tushadi?" },
        { title: "Bemor huquqlari", prompt: "Bemorni shoshilinch yordam ko'rsatmasdan qaytarish mumkinmi?" }
      ]
    },
    {
      category: "Ta'lim",
      items: [
        { title: "O'qishni ko'chirish", prompt: "Xorijdan yoki boshqa OTMdan o'qishni ko'chirish (perevod) tartibi." },
        { title: "Magistratura", prompt: "Magistraturaga kirishda til sertifikati talab qilinadimi?" },
        { title: "Bog'cha navbati", prompt: "Bolani bog'chaga joylashtirish uchun onlayn navbatga turish." },
        { title: "Kontrakt to'lovi", prompt: "O'qish kontraktini bo'lib to'lash imkoniyatlari bormi?" },
        { title: "Akademik ta'til", prompt: "Talabaga qanday hollarda akademik ta'til beriladi?" },
        { title: "Maktab imtiyozlari", prompt: "Ko'p bolali oilalar uchun maktabda qanday imtiyozlar bor?" }
      ]
    },
    {
      category: "Bojxona",
      items: [
        { title: "Bojxona to'lovlari", prompt: "Chet eldan tovar olib kirishda bojsiz limit miqdori qancha?" },
        { title: "Yashil yo'lak", prompt: "Aeroportda yashil va qizil yo'lakdan o'tish qoidalari." },
        { title: "Avtomobil rastamojka", prompt: "Chet eldan elektromobil olib kirishdagi bojxona imtiyozlari." },
        { title: "Valyuta olib chiqish", prompt: "O'zbekistondan qancha miqdorgacha naqd valyuta olib chiqish mumkin?" },
        { title: "Pochta jo'natmalari", prompt: "Chet eldan pochta orqali keladigan tovarlar uchun soliq bormi?" },
        { title: "Taqiqlangan mahsulotlar", prompt: "O'zbekistonga olib kirish taqiqlangan tovarlar ro'yxati." }
      ]
    },
    {
      category: "Ijtimoiy Himoya",
      items: [
        { title: "Bolalar puli", prompt: "Kam ta'minlangan oilalarga bolalar puli olish tartibi va miqdori." },
        { title: "Uy-joy subsidiyasi", prompt: "Uy-joy olish uchun davlat subsidiyasini kimlar olishi mumkin?" },
        { title: "Yolg'iz keksalar", prompt: "Yolg'iz yashaydigan qariyalarga qanday yordamlar beriladi?" },
        { title: "Moddiy yordam", prompt: "Mahalla orqali moddiy yordam olish shartlari qanday?" },
        { title: "Mehribonlik uyi", prompt: "Farzand asrab olish tartibi va talablari qanday?" },
        { title: "Ishsizlik nafaqasi", prompt: "Ishsiz deb ro'yxatga turish va nafaqa olish qoidalari." }
      ]
    },
    {
      category: "Sud va Protsess",
      items: [
        { title: "Sudga murojaat", prompt: "Sudga da'vo arizasi qanday yoziladi va topshiriladi?" },
        { title: "Elektron sud", prompt: "E-sud tizimi orqali masofadan turib sudga qatnashish tartibi." },
        { title: "Bepul advokat", prompt: "Davlat hisobidan bepul advokat olish uchun kimlar haqlimi?" },
        { title: "Sud qarori ijrosi", prompt: "Sud qarori ijro etilmasa MIBga qanday murojaat qilinadi?" },
        { title: "Apellyatsiya", prompt: "Sud qarori ustidan apellyatsiya shikoyati berish muddati." },
        { title: "Guvohlik berish", prompt: "Sudda guvoh sifatida qatnashish majburiyatlari va huquqlari." }
      ]
    },
    {
      category: "Soliqlar",
      items: [
        { title: "Daromad solig'i", prompt: "Jismoniy shaxslarning daromad solig'i stavkalari qancha?" },
        { title: "Mol-mulk solig'i", prompt: "Uy-joy va yer uchun soliq qachon va qayerga to'lanadi?" },
        { title: "Soliq keshbek", prompt: "Soliq hamkor ilovasida keshbekni qanday qaytarib olish mumkin?" },
        { title: "QQS (NDS)", prompt: "Tadbirkorlar uchun QQS to'lovchisi bo'lish qoidalari." },
        { title: "Soliq imtiyozlari", prompt: "Yosh oilalar va nogironligi bor shaxslar uchun soliq imtiyozlari." },
        { title: "Aylanma soliq", prompt: "Aylanmadan olinadigan soliqni hisoblash tartibi." }
      ]
    },
    {
      category: "Pensiya",
      items: [
        { title: "Pensiya yoshi", prompt: "O'zbekistonda erkaklar va ayollar uchun pensiya yoshi qancha?" },
        { title: "Pensiya hisoblash", prompt: "Pensiya miqdori ish staji va ish haqiga qanday bog'liq?" },
        { title: "Ish staji", prompt: "Staj yetmagan taqdirda pensiya olish imkoniyati bormi?" },
        { title: "Boquvchisini yo'qotgan", prompt: "Boquvchisini yo'qotganlik nafaqasini tayinlash tartibi." },
        { title: "Pensiya jamg'armasi", prompt: "Jamg'arib boriladigan pensiya tizimi qanday ishlaydi?" },
        { title: "Xorijda ishlash staji", prompt: "Chet elda ishlagan yillar pensiya hisoblashda inobatga olinadimi?" }
      ]
    },
    {
      category: "Iste'molchi Huquqlari",
      items: [
        { title: "Tovar qaytarish", prompt: "Sifatsiz mahsulotni qaytarish yoki almashtirish tartibi." },
        { title: "Kafolat muddati", prompt: "Kafolat muddati davrida bepul ta'mirlash huquqi." },
        { title: "Muddati o'tgan tovar", prompt: "Do'konda muddati o'tgan tovar sotilsa qayerga murojaat qilish kerak?" },
        { title: "Chek berilmasa", prompt: "Sotuvchi chek bermasa nima qilish kerak?" },
        { title: "Onlayn xaridlar", prompt: "Internet orqali olingan tovarlarni qaytarish qoidalari." },
        { title: "Narxlar farqi", prompt: "Vitrinadagi narx kassa narxidan farq qilsa qaysi biri to'lanadi?" }
      ]
    },
    {
      category: "Jinoyat Huquqi",
      items: [
        { title: "Advokat huquqi", prompt: "Ushlangan shaxsning birinchi navbatdagi huquqlari qanday?" },
        { title: "Tuhmat va haqorat", prompt: "Ijtimoiy tarmoqlarda haqorat qilganlik uchun qanday jazo bor?" },
        { title: "Firibgarlik", prompt: "Pulini firibgarga berib qo'ygan odam ariza bilan qayerga boradi?" },
        { title: "Amnistiya", prompt: "O'zbekistonda amnistiya va afv etish tartibi qanday?" },
        { title: "O'zini himoya qilish", prompt: "Zaruriy mudofaa chegarasidan chiqib ketish nima degani?" },
        { title: "Jarima jazosi", prompt: "Jinoyat uchun tayinlangan jarimani to'lash muddati va tartibi." }
      ]
    }
  ],
  [Language.RU]: [
    {
      category: "Семейное право",
      items: [
        { title: "Порядок развода", prompt: "Как подать на развод? Какие документы нужны для суда?" },
        { title: "Взыскание алиментов", prompt: "Как взыскать алименты? Каков их минимальный размер?" },
        { title: "Брачный договор", prompt: "Как оформить брачный контракт и что в нем прописать?" },
        { title: "Опека и попечительство", prompt: "Как оформить опекунство над ребенком?" },
        { title: "Насилие в семье", prompt: "Как получить охранный ордер при домашнем насилии?" },
        { title: "Раздел имущества", prompt: "Как делится совместно нажитое имущество при разводе?" }
      ]
    },
    {
      category: "Трудовое право",
      items: [
        { title: "Трудовой отпуск", prompt: "Сколько дней длится ежегодный отпуск по новому ТК?" },
        { title: "Увольнение", prompt: "Законные основания для увольнения работника по инициативе работодателя." },
        { title: "Задержка зарплаты", prompt: "Что делать, если задерживают зарплату? Куда жаловаться?" },
        { title: "Декретный отпуск", prompt: "Кто и как выплачивает пособие по беременности и родам?" },
        { title: "Испытательный срок", prompt: "Правила и максимальный срок испытательного срока при приеме на работу." },
        { title: "Трудовой договор", prompt: "Правила заключения трудового договора согласно кодексу 2023 года." }
      ]
    },
    {
      category: "Имущество и Жилье",
      items: [
        { title: "Купля-продажа жилья", prompt: "Какие документы требует нотариус при покупке квартиры?" },
        { title: "Договор аренды", prompt: "Обязательно ли регистрировать договор аренды в налоговой?" },
        { title: "Оформление наследства", prompt: "Когда и как вступать в наследство после смерти родственника?" },
        { title: "Снос (Снос)", prompt: "Как рассчитывается компенсация при сносе жилого дома?" },
        { title: "Прописка", prompt: "Новые правила постоянной регистрации в Ташкенте." },
        { title: "Кадастр", prompt: "Что делать при утере кадастрового паспорта на недвижимость?" }
      ]
    },
    {
      category: "Авто и ПДД",
      items: [
        { title: "Оплата штрафов", prompt: "Как оплатить штраф онлайн и получить скидку 50%?" },
        { title: "Тонировка стекол", prompt: "Цены на разрешение на тонировку и процесс оформления." },
        { title: "ДТП (Авария)", prompt: "Порядок получения страховых выплат при совершении ДТП." },
        { title: "Доверенность", prompt: "Виды доверенностей на управление транспортным средством." },
        { title: "Газовый баллон", prompt: "Нужно ли разрешение на установку ГБО на автомобиль?" },
        { title: "Штрафстоянка", prompt: "В каких случаях автомобиль могут забрать на штрафстоянку?" }
      ]
    },
    {
      category: "Банк и Финансы",
      items: [
        { title: "Кредитная история", prompt: "Как проверить и исправить свою кредитную историю?" },
        { title: "Ипотечный кредит", prompt: "Условия ипотеки для молодых семей в Узбекистане." },
        { title: "Мошенничество с картами", prompt: "Несет ли банк ответственность при краже денег с карты?" },
        { title: "Микрозайм", prompt: "Какие документы нужны для получения быстрого микрозайма?" },
        { title: "Банковские вклады", prompt: "Гарантируются ли государством вклады физических лиц?" },
        { title: "Возврат кредита", prompt: "Последствия невозможности выплаты банковского кредита." }
      ]
    },
    {
      category: "Миграция и Виза",
      items: [
        { title: "Загранпаспорт", prompt: "Порядок, сроки и стоимость получения загранпаспорта." },
        { title: "Работа за рубежом", prompt: "Как легально уехать на работу через Агентство внешней миграции?" },
        { title: "Гражданство РУз", prompt: "Упрощенный порядок получения гражданства Узбекистана." },
        { title: "Депортация", prompt: "Как проверить наличие запрета на въезд (депортации)?" },
        { title: "Временная прописка", prompt: "Правила регистрации иностранных граждан в Узбекистане." },
        { title: "Рабочая виза", prompt: "Как получить разрешение на работу иностранцу в Узбекистане?" }
      ]
    },
    {
      category: "Бизнес",
      items: [
        { title: "Открытие ИП", prompt: "Порядок регистрации индивидуального предпринимателя и налоги." },
        { title: "Создание ООО", prompt: "Список документов и минимальный уставной фонд для открытия ООО." },
        { title: "Лицензирование", prompt: "Для каких видов деятельности требуется лицензия?" },
        { title: "Субсидии бизнесу", prompt: "Какие виды государственной поддержки есть для предпринимателей?" },
        { title: "Экспорт и Импорт", prompt: "Таможенное оформление при экспорте товаров из Узбекистана." },
        { title: "Франчайзинг", prompt: "Правовые основы заключения договора франшизы." }
      ]
    },
    {
      category: "Здравоохранение",
      items: [
        { title: "Группа инвалидности", prompt: "Порядок установления группы инвалидности и льготы." },
        { title: "Бесплатные лекарства", prompt: "При каких заболеваниях полагаются бесплатные медикаменты?" },
        { title: "Получение ордера", prompt: "Как получить ордер на бесплатное лечение в госклиниках?" },
        { title: "Частная клиника", prompt: "Куда жаловаться на врачебную ошибку в частной клинике?" },
        { title: "Страхование", prompt: "Как работает система обязательного медицинского страхования?" },
        { title: "Права пациента", prompt: "Могут ли отказать в госпитализации при экстренном случае?" }
      ]
    },
    {
      category: "Образование",
      items: [
        { title: "Перевод учебы", prompt: "Порядок перевода (перевода) из зарубежного или другого ВУЗа." },
        { title: "Магистратура", prompt: "Нужен ли языковой сертификат для поступления в магистратуру?" },
        { title: "Очередь в сад", prompt: "Как встать в онлайн-очередь в детский сад через my.gov.uz?" },
        { title: "Оплата контракта", prompt: "Есть ли льготы или рассрочка при оплате контракта на обучение?" },
        { title: "Академ. отпуск", prompt: "В каких случаях студенту предоставляется академический отпуск?" },
        { title: "Школьные льготы", prompt: "Какие льготы в школах есть для многодетных семей?" }
      ]
    },
    {
      category: "Таможня",
      items: [
        { title: "Таможенные пошлины", prompt: "Каков лимит беспошлинного ввоза товаров для личного пользования?" },
        { title: "Зеленый коридор", prompt: "Правила прохождения зеленого и красного коридора в аэропорту." },
        { title: "Растаможка авто", prompt: "Льготы при ввозе электромобилей в Узбекистан." },
        { title: "Вывоз валюты", prompt: "Какую сумму наличной валюты можно вывозить без декларации?" },
        { title: "Почтовые посылки", prompt: "Налоги на товары, заказанные через интернет-магазины из-за рубежа." },
        { title: "Запрещенные товары", prompt: "Список товаров, запрещенных к ввозу в Республику Узбекистан." }
      ]
    },
    {
      category: "Соцзащита",
      items: [
        { title: "Детские пособия", prompt: "Порядок получения и размер пособия на детей для малообеспеченных семей." },
        { title: "Субсидия на жилье", prompt: "Кто имеет право на получение государственной субсидии на покупку жилья?" },
        { title: "Одинокие пожилые", prompt: "Какая социальная помощь оказывается одиноким пенсионерам?" },
        { title: "Материальная помощь", prompt: "Условия получения материальной помощи через махаллю." },
        { title: "Усыновление", prompt: "Порядок и требования к кандидатам на усыновление ребенка." },
        { title: "Пособие по безработице", prompt: "Как встать на учет по безработице и получать выплаты?" }
      ]
    },
    {
      category: "Суд и Процесс",
      items: [
        { title: "Обращение в суд", prompt: "Как правильно составить и подать исковое заявление в суд?" },
        { title: "Электронный суд", prompt: "Участие в судебном процессе дистанционно через систему E-sud." },
        { title: "Бесплатный адвокат", prompt: "Кто имеет право на адвоката за счет государства?" },
        { title: "Исполнение решений", prompt: "Куда обращаться в БПИ, если судебное решение не выполняется?" },
        { title: "Апелляция", prompt: "Сроки и порядок подачи апелляционной жалобы на решение суда." },
        { title: "Свидетель в суде", prompt: "Права и обязанности свидетеля в гражданском и уголовном процессе." }
      ]
    },
    {
      category: "Налоги",
      items: [
        { title: "Подоходный налог", prompt: "Ставки подоходного налога для физических лиц в Узбекистане." },
        { title: "Налог на имущество", prompt: "Когда и как оплачивать налог на недвижимость и землю?" },
        { title: "Налоговый кэшбэк", prompt: "Как вернуть 1% кэшбэка через приложение Soliq?" },
        { title: "НДС для бизнеса", prompt: "Правила перехода на уплату НДС для предпринимателей." },
        { title: "Налоговые льготы", prompt: "Льготы по налогам для лиц с инвалидностью и молодых семей." },
        { title: "Налог с оборота", prompt: "Порядок расчета и уплаты налога с оборота для малого бизнеса." }
      ]
    },
    {
      category: "Пенсия",
      items: [
        { title: "Пенсионный возраст", prompt: "Во сколько лет выходят на пенсию мужчины и женщины в РУз?" },
        { title: "Расчет пенсии", prompt: "Как зависит размер пенсии от стажа и среднемесячной зарплаты?" },
        { title: "Трудовой стаж", prompt: "Можно ли получать пенсию при неполном трудовом стаже?" },
        { title: "Потеря кормильца", prompt: "Порядок назначения пособия по случаю потери кормильца." },
        { title: "Пенсионный фонд", prompt: "Как работает система накопительного пенсионного обеспечения?" },
        { title: "Стаж за рубежом", prompt: "Учитываются ли годы работы за границей при расчете пенсии в РУз?" }
      ]
    },
    {
      category: "Права потребителей",
      items: [
        { title: "Возврат товара", prompt: "Порядок возврата или обмена товара ненадлежащего качества." },
        { title: "Гарантийный срок", prompt: "Право на бесплатный ремонт в течение гарантийного периода." },
        { title: "Просроченный товар", prompt: "Что делать, если в магазине продали продукт с истекшим сроком годности?" },
        { title: "Отсутствие чека", prompt: "Можно ли вернуть товар, если чек был утерян?" },
        { title: "Онлайн-покупки", prompt: "Правила возврата товаров, купленных через интернет-магазины." },
        { title: "Разница в цене", prompt: "Какую цену обязан пробить кассир, если она отличается от ценника?" }
      ]
    },
    {
      category: "Уголовное право",
      items: [
        { title: "Права при задержании", prompt: "Каковы первые действия и права гражданина при задержании?" },
        { title: "Клевета и оскорбление", prompt: "Ответственность за оскорбление личности в социальных сетях." },
        { title: "Мошенничество", prompt: "Куда подавать заявление, если вы стали жертвой онлайн-мошенников?" },
        { title: "Амнистия", prompt: "Как работает система амнистии и помилования в Узбекистане?" },
        { title: "Самооборона", prompt: "Что является превышением пределов необходимой обороны?" },
        { title: "Штрафы за преступления", prompt: "Сроки и порядок выплаты уголовных штрафов." }
      ]
    }
  ],
  [Language.EN]: [
    {
      category: "Family Law",
      items: [
        { title: "Divorce Procedure", prompt: "What is the procedure for divorce? What documents are needed for court?" },
        { title: "Alimony Collection", prompt: "How to claim alimony? What is the minimum amount in Uzbekistan?" },
        { title: "Prenuptial Agreement", prompt: "How to draft a marriage contract and what should it include?" },
        { title: "Custody", prompt: "What is the legal process for obtaining child custody?" },
        { title: "Domestic Violence", prompt: "How to obtain a protection order in case of domestic violence?" },
        { title: "Property Division", prompt: "How is joint property divided during a divorce?" }
      ]
    },
    {
      category: "Labor Law",
      items: [
        { title: "Annual Leave", prompt: "How many days is the minimum annual leave under the 2023 Labor Code?" },
        { title: "Termination", prompt: "What are the legal grounds for terminating an employee?" },
        { title: "Salary Delay", prompt: "What to do if salary is delayed? What are the penalties for employers?" },
        { title: "Maternity Leave", prompt: "Who pays for pregnancy and childbirth benefits in Uzbekistan?" },
        { title: "Probation Period", prompt: "What are the rules and maximum duration for a probation period?" },
        { title: "Labor Contract", prompt: "Rules for drafting a labor contract according to the new code." }
      ]
    },
    {
      category: "Property & Housing",
      items: [
        { title: "Buying Real Estate", prompt: "What documents does a notary require when buying an apartment?" },
        { title: "Rental Agreement", prompt: "Is it mandatory to register a rental agreement with the tax authorities?" },
        { title: "Inheritance", prompt: "How and when to claim inheritance after the death of a relative?" },
        { title: "Demolition (Snos)", prompt: "How is compensation calculated when a house is scheduled for demolition?" },
        { title: "Residency (Propiska)", prompt: "What are the new rules for permanent residency in Tashkent?" },
        { title: "Cadastral Document", prompt: "What to do if the property's cadastral passport is lost?" }
      ]
    },
    {
      category: "Auto & Traffic",
      items: [
        { title: "Paying Fines", prompt: "How to pay a traffic fine online and get a 50% discount?" },
        { title: "Window Tinting", prompt: "Costs for window tinting permits and the application process." },
        { title: "Car Accident", prompt: "What is the procedure for claiming insurance after a car accident?" },
        { title: "Power of Attorney", prompt: "Types of power of attorney for driving a vehicle in Uzbekistan." },
        { title: "Gas Cylinder (GBO)", prompt: "Do I need a permit to install a gas cylinder on my car?" },
        { title: "Drunk Driving", prompt: "What are the penalties for driving under the influence?" }
      ]
    },
    {
      category: "Bank & Finance",
      items: [
        { title: "Credit History", prompt: "How can I check and improve my credit history in Uzbekistan?" },
        { title: "Mortgage Loans", prompt: "What are the mortgage conditions for young families?" },
        { title: "Card Fraud", prompt: "Is the bank liable if money is stolen from my plastic card?" },
        { title: "Microloans", prompt: "What documents are required to get a quick microloan?" },
        { title: "Bank Deposits", prompt: "Are personal bank deposits guaranteed by the state?" },
        { title: "Loan Repayment", prompt: "What are the consequences of failing to repay a bank loan?" }
      ]
    },
    {
      category: "Migration & Visa",
      items: [
        { title: "Foreign Passport", prompt: "Procedure, timeline, and cost for obtaining a passport for international travel." },
        { title: "Working Abroad", prompt: "How to legally work abroad through the External Migration Agency?" },
        { title: "Citizenship", prompt: "What is the simplified procedure for obtaining Uzbek citizenship?" },
        { title: "Deportation", prompt: "How to check if there is an entry ban or deportation record?" },
        { title: "Temporary Registration", prompt: "Rules for registering foreign citizens visiting Uzbekistan." },
        { title: "Work Visa", prompt: "How to obtain a work permit for a foreign citizen in Uzbekistan?" }
      ]
    },
    {
      category: "Business",
      items: [
        { title: "Starting an IE", prompt: "Registration process for an Individual Entrepreneur and tax obligations." },
        { title: "Forming an LLC", prompt: "List of documents and minimum capital required to open an LLC." },
        { title: "Licensing", prompt: "Which business activities require a special license?" },
        { title: "State Subsidies", prompt: "What kind of government support is available for entrepreneurs?" },
        { title: "Export & Import", prompt: "Customs clearance procedures for exporting goods from Uzbekistan." },
        { title: "Franchising", prompt: "Legal basis for signing a franchise agreement." }
      ]
    },
    {
      category: "Healthcare",
      items: [
        { title: "Disability Group", prompt: "Procedure for determining a disability group and associated benefits." },
        { title: "Free Medications", prompt: "For which diseases are free medicines provided by law?" },
        { title: "Medical Orders", prompt: "How to get a state order for free treatment in specialized clinics?" },
        { title: "Private Clinics", prompt: "Where to file a complaint regarding medical errors in private clinics?" },
        { title: "Health Insurance", prompt: "How does the mandatory medical insurance system work?" },
        { title: "Patient Rights", prompt: "Can a hospital refuse admission in an emergency case?" }
      ]
    },
    {
      category: "Education",
      items: [
        { title: "Student Transfer", prompt: "Procedure for transferring from a foreign or domestic university." },
        { title: "Master's Degree", prompt: "Is a language certificate required for Master's degree admission?" },
        { title: "Kindergarten Queue", prompt: "How to join the online queue for a state kindergarten?" },
        { title: "Tuition Fees", prompt: "Are there installment plans or tax benefits for tuition payments?" },
        { title: "Academic Leave", prompt: "Under what circumstances can a student take an academic leave?" },
        { title: "School Benefits", prompt: "What benefits are available in schools for large families?" }
      ]
    },
    {
      category: "Customs",
      items: [
        { title: "Customs Duties", prompt: "What is the duty-free limit for importing goods for personal use?" },
        { title: "Green Channel", prompt: "Rules for green and red channels at the airport." },
        { title: "Car Customs", prompt: "Customs benefits for importing electric vehicles into Uzbekistan." },
        { title: "Currency Export", prompt: "How much cash currency can be exported without a declaration?" },
        { title: "Postal Packages", prompt: "Taxes on goods ordered from international online shops." },
        { title: "Prohibited Goods", prompt: "List of items prohibited for import into the Republic of Uzbekistan." }
      ]
    },
    {
      category: "Social Protection",
      items: [
        { title: "Child Benefits", prompt: "Procedure and amount of child benefits for low-income families." },
        { title: "Housing Subsidy", prompt: "Who is eligible for a state subsidy to purchase a home?" },
        { title: "Elderly Care", prompt: "What social assistance is provided to elderly people living alone?" },
        { title: "Financial Aid", prompt: "Conditions for receiving financial aid through the local Mahalla." },
        { title: "Adoption", prompt: "Procedure and requirements for adopting a child in Uzbekistan." },
        { title: "Unemployment", prompt: "How to register as unemployed and receive welfare benefits?" }
      ]
    },
    {
      category: "Court & Process",
      items: [
        { title: "Filing a Lawsuit", prompt: "How to correctly draft and submit a claim to the court?" },
        { title: "Electronic Court", prompt: "Participating in court hearings remotely via the E-sud system." },
        { title: "Free Lawyer", prompt: "Who is entitled to a state-funded defense attorney?" },
        { title: "Enforcement", prompt: "How to contact the Bureau of Compulsory Enforcement (MIB)?" },
        { title: "Appeals", prompt: "Timeline and procedure for appealing a court decision." },
        { title: "Witness Rights", prompt: "Rights and obligations of a witness in a judicial proceeding." }
      ]
    },
    {
      category: "Taxes",
      items: [
        { title: "Income Tax", prompt: "What are the personal income tax rates in Uzbekistan?" },
        { title: "Property Tax", prompt: "When and where to pay taxes for real estate and land?" },
        { title: "Tax Cashback", prompt: "How to claim the 1% cashback via the Soliq mobile app?" },
        { title: "VAT for Business", prompt: "Rules for registering as a VAT payer for entrepreneurs." },
        { title: "Tax Exemptions", prompt: "Tax benefits for disabled individuals and young families." },
        { title: "Turnover Tax", prompt: "How to calculate and pay turnover tax for small businesses." }
      ]
    },
    {
      category: "Pension",
      items: [
        { title: "Retirement Age", prompt: "What is the retirement age for men and women in Uzbekistan?" },
        { title: "Pension Calculation", prompt: "How does the pension amount depend on years of service and salary?" },
        { title: "Work Experience", prompt: "Is it possible to receive a pension with incomplete work experience?" },
        { title: "Survivor Pension", prompt: "Procedure for assigning a pension in case of the loss of a breadwinner." },
        { title: "Pension Fund", prompt: "How does the cumulative pension system work?" },
        { title: "Work Abroad", prompt: "Are years worked abroad considered for pension calculation?" }
      ]
    },
    {
      category: "Consumer Rights",
      items: [
        { title: "Returning Goods", prompt: "Procedure for returning or exchanging a defective product." },
        { title: "Warranty Period", prompt: "Right to free repair during the warranty period." },
        { title: "Expired Goods", prompt: "What to do if a store sells an expired product?" },
        { title: "Lost Receipt", prompt: "Can I return a product if the receipt was lost?" },
        { title: "Online Shopping", prompt: "Rules for returning items bought through online stores." },
        { title: "Price Difference", prompt: "Which price should be charged if the shelf price differs from the POS?" }
      ]
    },
    {
      category: "Criminal Law",
      items: [
        { title: "Right to a Lawyer", prompt: "What are the immediate rights of a person when detained?" },
        { title: "Slander & Insult", prompt: "Penalties for personal insults on social media platforms." },
        { title: "Fraud", prompt: "Where to file a report if you become a victim of online fraud?" },
        { title: "Amnesty", prompt: "How does the amnesty and pardon system work in Uzbekistan?" },
        { title: "Self-Defense", prompt: "What constitutes exceeding the limits of necessary self-defense?" },
        { title: "Criminal Fines", prompt: "Timelines and procedures for paying criminal fines." }
      ]
    }
  ]
};

export const TRANSLATIONS = {
  [Language.UZ]: {
    profileLoginPrompt: "Profilingizni boshqarish uchun tizimga kiring.",
    profileLoginBtn: "Kirish / Ro'yxatdan o'tish",
    title: "LAWIFY",
    subtitle: "O'zbekiston bo'yicha huquqiy yordamchi",
    settings: "Sozlamalar",
    length: "Javob uzunligi",
    tone: "Ohang",
    style: "Uslub",
    clarify: "Aniqlovchi savollar",
    short: "Qisqa",
    medium: "O'rtacha",
    detailed: "Batafsil",
    simple: "Oddiy",
    professional: "Rasmiy",
    bullets: "Belgilar bilan",
    steps: "Qadamma-qadam",
    paragraphs: "Matn ko'rinishida",
    docType: "Hujjat turi",
    docGeneral: "Umumiy Maslahat",
    docContract: "Shartnoma",
    docLetter: "Rasmiy Xat",
    docApp: "Ariza",
    perspective: "Yondashuv",
    persNeutral: "Xolis",
    persConsumer: "Mijoz himoyasi",
    persBusiness: "Biznes himoyasi",
    inputPlaceholder: "Huquqiy savolingizni yozing...",
    disclaimer: "Bu yuridik maslahat emas. Shoshilinch hollarda advokatga murojaat qiling.",
    startLive: "Jonli suhbat",
    stopLive: "Suhbatni tugatish",
    speaking: "Gapirilmoqda...",
    listening: "Eshitilmoqda...",
    send: "Yuborish",
    uploadImage: "Rasm yuklash",
    uploadDoc: "Hujjat yuklash",
    audioPermission: "Mikrofon ruxsati kerak",
    thinking: "O'ylanmoqda...",
    fileSelected: "Hujjat tanlandi",
    connectedSources: "Ulangan manbalar: 19 Kodeks & Lex.uz",
    sourcesTitle: "RASMIY MANBALAR",
    navDashboard: "Bosh sahifa",
    navChat: "AI Yurist",
    navOdilbek: "Odilbek (Tushuntirish)",
    navTemplates: "AI Kotib", 
    navHistory: "Tarix",
    navTopics: "Mavzular",
    navProfile: "Profil",
    navPlans: "Tariflar",
    upgradeBtn: "Premiumga o'tish",
    dashboardWelcome: "Xush kelibsiz",
    dashboardSubtitle: "Bugun sizga qanday yuridik yordam bera olaman?",
    quickChat: "Yangi suhbat",
    quickChatDesc: "AI bilan huquqiy maslahat",
    quickContracts: "Hujjat tekshirish",
    quickContractsDesc: "Shartnomalarni tahlil qilish",
    quickTemplates: "AI Kotib",
    quickTemplatesDesc: "Hujjatlarni avtomatlashtirish",
    openApp: "Ilovani ochish",
    didYouKnowTitle: "O'zbekistonning Yangi Mehnat Kodeksi",
    didYouKnowContent: "2023-yilgi yangi Mehnat kodeksi xodimlar huquqlari, ta'til hisoblash va masofaviy ishlash bo'yicha muhim o'zgarishlarni kiritdi.",
    didYouKnowButton: "Batafsil so'rash",
    didYouKnowTag: "Bilasizmi?",
    quickLinksTitle: "Tezkor Havolalar",
    qlFamily: "Oila Huquqi",
    qlLabor: "Mehnat Kodeksi",
    qlCriminal: "Jinoyat Kodeksi",
    qlBusiness: "Biznes Huquqi",
    qlHousing: "Uy-joy Huquqi",
    qlAdmin: "Ma'muriy Javobgarlik",
    qlBank: "Bank va Kredit",
    qlHealth: "Sog'liqni Saqlash",
    qlEdu: "Ta'lim Huquqi",
    qlCustoms: "Bojxona",
    qlTax: "Soliqlar",
    qlPension: "Pensiya",
    qlFamilyPrompt: "Oila huquqi bo'yicha savolim bor.",
    qlLaborPrompt: "Mehnat kodeksi bo'yicha ma'lumot kerak.",
    qlCriminalPrompt: "Jinoyat kodeksi bo'yicha savolim bor.",
    qlHousingPrompt: "Uy-joy huquqi bo'yicha savolim bor.",
    qlBusinessPrompt: "Biznes bo'yicha yuridik maslahat kerak.",
    qlAdminPrompt: "Ma'muriy javobgarlik bo'yicha savol.",
    qlBankPrompt: "Bank krediti va omonatlar bo'yicha savolim bor.",
    qlHealthPrompt: "Tibbiy xizmatlar va bemor huquqlari bo'yicha savol.",
    qlEduPrompt: "Ta'lim olish, kontrakt va o'qishni ko'chirish bo'yicha savol.",
    qlCustomsPrompt: "Bojxona to'lovlari va qoidalari haqida ma'lumot kerak.",
    qlTaxPrompt: "Soliq turlari va imtiyozlar haqida so'ramoqchiman.",
    qlPensionPrompt: "Pensiya yoshi va hisoblash tartibi bo'yicha savol.",
    visTitle: "KELAJAK REJALARI",
    visAutoAgents: "Avtonom Yuridik Agentlar",
    visAutoAgentsDesc: "Hujjatlarni mustaqil tayyorlaydigan va muzokara olib boradigan AI agentlar.",
    visCourtAPI: "Sud Tizimi Integratsiyasi",
    visCourtAPIDesc: "Real vaqt rejimida ishlarni kuzatish uchun E-Sud tizimi bilan integratsiya.",
    visBlockchain: "Blokcheyn Notarius",
    visBlockchainDesc: "Milliy blokcheyn orqali shartnomalarni o'zgarmas tasdiqlash.",
    visAIJudge: "AI Sud Yordamchisi Pilot",
    visAIJudgeDesc: "Sud yuklamasini kamaytirish uchun dastlabki ish baholash tizimi.",
    statPlatformImpact: "PLATFORMA NATIJALARI",
    statUsers: "Faol Foydalanuvchilar",
    statDocs: "Yaratilgan Hujjatlar",
    statAccuracy: "Yuridik Aniqlik",
    statAIAvailability: "AI Mavjudligi",
    statLanguages: "Tillar",
    statSystemOp: "Tizim Ishlamoqda",
    footerCopyright: "Lawify Inc. © 2026",
    techTitle: "Ishonchli Texnologiya",
    techSecure: "Xavfsiz va Shifrlangan",
    techModel: "Ixtisoslashgan AI",
    techModelSub: "Gallyutsinatsiyasiz",
    techDatabase: "Lex.uz Bazasi",
    libraryTitle: "Yuridik hujjatlar kutubxonasi",
    librarySubtitle: "AI Kotib yordamida har qanday hujjatni tezkor tayyorlang.",
    librarySelectPrompt: "Hujjatni boshlash uchun andozani tanlang.",
    libraryDifficulty: "Murakkablik",
    libraryComingSoon: "Tez orada",
    libraryFooter: "Barcha andozalar O'zbekiston Respublikasi qonunchiligiga to'liq mos keladi va yuristlar tomonidan tasdiqlangan.",
    catCivil: "Fuqarolik",
    catProperty: "Mulkiy",
    catFamily: "Oila",
    catBusiness: "Biznes",
    catAdmin: "Ma'muriy",
    tDebtTitle: "Qarz Tilxati",
    tDebtDesc: "Qarz berish yoki olishni rasmiylashtirish uchun.",
    tRentTitle: "Ijara Shartnomasi",
    tRentDesc: "Turar joy yoki ofis ijarasi uchun.",
    tDivorceTitle: "Ajrashish uchun Ariza",
    tDivorceDesc: "Sudga taqdim etiladigan rasmiy ariza.",
    tLaborTitle: "Mehnat Shartnomasi",
    tLaborDesc: "Ish beruvchi va xodim o'rtasidagi kelishuv.",
    tPowerTitle: "Ishonchnoma",
    tPowerDesc: "Avtomobil yoki mulkni boshqarish huquqi.",
    tComplaintTitle: "Shikoyat Ariza",
    tComplaintDesc: "Davlat organlari ustidan shikoyat.",
    tDebtPrompt: "Men qarz tilxatini yozmoqchiman. Iltimos, huquqiy jihatdan to'g'ri hujjat tayyorlash uchun mendan kerakli barcha ma'lumotlarni (tomonlar, summa, muddat) so'rang.",
    tRentPrompt: "Men turar joy ijara shartnomasini tuzmoqchiman. Iltimos, shartnoma qonuniy bo'lishi uchun mendan kerakli ma'lumotlarni so'rang va keyin shartnoma matnini tayyorlab bering.",
    tDivorcePrompt: "Men sudga ajrashish uchun ariza yozmoqchiman. Iltimos, arizani to'g'ri shakllantirish uchun mendan talab qilinadigan ma'lumotlarni so'rang.",
    tLaborPrompt: "Men yangi Mehnat kodeksi bo'yicha mehnat shartnomasini tuzmoqchiman. Iltimos, ish beruvchi va xodim haqidagi kerakli ma'lumotlarni so'rang.",
    tPowerPrompt: "Menga avtomobil yoki mulkni boshqarish uchun ishonchnoma kerak. Iltimos, ishonchnoma turini va taraflar ma'lumotlarini mendan so'rang.",
    tComplaintPrompt: "Men davlat organiga shikoyat yozmoqchiman. Iltimos, vaziyatni o'rganish uchun mendan kerakli savollarni so'rang, so'ngra shikoyat matnini yozib bering.",
    diffEasy: "Oson",
    diffMedium: "O'rta",
    diffHard: "Qiyin",
    topicsTitle: "Umumiy huquqiy mavzular",
    topicsSubtitle: "Formani oldindan to'ldirish uchun mavzuni tanlang",
    historyTitle: "Murojaatlar tarixi",
    historySubtitle: "Sizning avvalgi suhbatlaringiz ushbu qurilmada saqlanadi.",
    historyClear: "Tarixni tozalash",
    historyEmpty: "Hozircha tarix yo'q. Yangi suhbat boshlang.",
    historyMessages: "xabar",
    profileTitle: "Foydalanuvchi Profili",
    profileSubtitle: "Shaxsiy ma'lumotlar va sozlamalarni boshqarish",
    profileName: "Ism",
    profileEmail: "Email",
    profileStats: "Statistika",
    profileConsultations: "Konsultatsiyalar",
    profileSavedDocs: "Saqlangan Hujjatlar",
    profileSave: "Saqlash",
    filterTitle: "Filtrlash",
    filterDate: "Sana",
    filterRole: "Kimdan",
    filterAll: "Barchasi",
    filterUser: "Foydalanuvchi",
    filterAI: "AI Yurist",
    filterLast24h: "Oxirgi 24 soat",
    filterLastWeek: "Oxirgi hafta",
    filterAllTime: "Barcha vaqt",
    plansTitle: "Tarif rejalari",
    plansSubtitle: "Ehtiyojingizga mos tarifni tanlang. Istalgan vaqtda bekor qilish mumkin.",
    currentPlan: "Joriy Tarif",
    subscribe: "Tanlash",
    featRequestLimit: "so'rov / kun",
    featUnlimited: "Cheksiz so'rovlar",
    featDocs: "ta hujjat tahlili",
    featNoDocs: "Hujjat yuklab bo'lmaydi",
    featSpeedNormal: "Standart tezlik",
    featSpeedFast: "Yuqori tezlik (Pro)",
    featLive: "Jonli ovozli suhbat",
    featLiveLimit: "daq/kun",
    featReasoning: "Chuqur huquqiy tahlil",
    featSupport: "Mijozlarni qo'llab-quvvatlash",
    featMobile: "Mobil qurilmalarda ishlash",
    featHistory: "Tarixni saqlash",
    featAds: "Reklamasiz interfeys",
    featExport: "Hujjatlarni PDF formatda yuklash",
    pFreeName: "Bepul",
    pFreePrice: "0",
    pDayName: "Kunlik Pro",
    pDayPrice: "15 000",
    pWeekName: "Haftalik Pro",
    pWeekPrice: "49 000",
    pMonthName: "Oylik Pro",
    pMonthPrice: "119 000",
    pLawyerName: "Yurist Pro",
    pLawyerPrice: "299 000",
    currency: "so'm",
    bestValue: "Eng Foydali",
    limitReachedTitle: "Kunlik limit tugadi",
    limitReachedBody: "Bugungi bepul 5 ta savol limitidan foydalandingiz.",
    limitUpgrade: "Pro tariflarni ko'rish",
    limitReturn: "Ertaga qaytish",
    freeUsage: "Bepul so'rovlar:",
    odilbekTitle: "Odilbek AI - Yuridik Tushuntiruvchi",
    odilbekSubtitle: "AI Yurist maslahatlarini oddiy tilda tushuntirib beraman. Cheklovsiz so'rang!",
    odilbekWelcome: "Assalomu alaykum! Men Odilbekman (Oksford Magistri). Advokatimiz bergan maslahat tushunarsiz bo'ldimi? Menga yuboring, oddiy qilib tushuntirib beraman.",
    askOdilbek: "Odilbekdan so'rash (Cheklovsiz)",
    odilbekAction: "Tushuntirib berish",
    odilbekPlaceholder: "Odilbekdan xohlagan narsangizni so'rang...",
  },
  [Language.RU]: {
    profileLoginPrompt: "Пожалуйста, войдите в систему, чтобы управлять профилем и подпиской.",
    profileLoginBtn: "Войти / Регистрация",
    title: "LAWIFY",
    subtitle: "Юридический помощник по Узбекистану",
    settings: "Настройки",
    length: "Длина ответа",
    tone: "Тон",
    style: "Стиль",
    clarify: "Уточняющие вопросы",
    short: "Краткий",
    medium: "Средний",
    detailed: "Подробный",
    simple: "Простой",
    professional: "Профессиональный",
    bullets: "Маркированный список",
    steps: "Пошагово",
    paragraphs: "Текстом",
    docType: "Тип документа",
    docGeneral: "Общая консультация",
    docContract: "Договор",
    docLetter: "Официальное письмо",
    docApp: "Заявление",
    perspective: "Позиция",
    persNeutral: "Нейтральная",
    persConsumer: "Защита потребителя",
    persBusiness: "Защита бизнеса",
    inputPlaceholder: "Задайте ваш юридический вопрос...",
    disclaimer: "Это информационная справка, а не замена юристу. В срочных случаях обратитесь к адвокату.",
    startLive: "Живой чат",
    stopLive: "Завершить",
    speaking: "Говорит...",
    listening: "Слушает...",
    send: "Отправить",
    uploadImage: "Загрузить фото",
    uploadDoc: "Загрузить документ",
    audioPermission: "Требуется разрешение на микрофон",
    thinking: "Думаю...",
    fileSelected: "Документ выбран",
    connectedSources: "Источники: 19 Кодексов & Lex.uz",
    sourcesTitle: "ОФИЦИАЛЬНЫЕ ИСТОЧНИКИ",
    navDashboard: "Главная",
    navChat: "AI Юрист",
    navOdilbek: "Одилбек (Объяснение)",
    navTemplates: "AI Секретарь",
    navHistory: "История",
    navTopics: "Темы",
    navProfile: "Профиль",
    navPlans: "Тарифы",
    upgradeBtn: "Купить Premium",
    dashboardWelcome: "Добро пожаловать",
    dashboardSubtitle: "Чем я могу помочь вам сегодня в правовых вопросах?",
    quickChat: "Новый чат",
    quickChatDesc: "Консультация с ИИ",
    quickContracts: "Анализ документов",
    quickContractsDesc: "Проверка договоров",
    quickTemplates: "AI Секретарь",
    quickTemplatesDesc: "Подготовка документов",
    openApp: "Открыть приложение",
    didYouKnowTitle: "Новый Трудовой Кодекс Узбекистана",
    didYouKnowContent: "Новый Трудовой кодекс 2023 года внес значительные изменения в права работников, расчет отпусков и правила удаленной работы.",
    didYouKnowButton: "Узнать подробнее",
    didYouKnowTag: "Знаете ли вы?",
    quickLinksTitle: "Быстрые Ссылки",
    qlFamily: "Семейное Право",
    qlLabor: "Трудовой Кодекс",
    qlCriminal: "Уголовный Кодекс",
    qlBusiness: "Бизнес Право",
    qlHousing: "Жилищное Право",
    qlAdmin: "Админ. Право",
    qlBank: "Банк и Кредит",
    qlHealth: "Здравоохранение",
    qlEdu: "Образование",
    qlCustoms: "Таможня",
    qlTax: "Налоги",
    qlPension: "Пенсия",
    qlFamilyPrompt: "У меня вопрос по семейному праву.",
    qlLaborPrompt: "Мне нужна информация по Трудовому кодексу.",
    qlCriminalPrompt: "У меня вопрос по Уголовному кодексу.",
    qlHousingPrompt: "У меня вопрос по жилищному праву.",
    qlBusinessPrompt: "Мне нужна юридическая консультация для бизнеса.",
    qlAdminPrompt: "Вопрос об административной ответственности.",
    qlBankPrompt: "Вопрос по банковским кредитам и вкладам.",
    qlHealthPrompt: "Вопрос по медицинским услугам и правам пациентов.",
    qlEduPrompt: "Вопрос по образованию, контрактам и переводу.",
    qlCustomsPrompt: "Вопрос по таможенным пошлинам и правилам.",
    qlTaxPrompt: "Вопрос по налогам и льготам.",
    qlPensionPrompt: "Вопрос по пенсионному возрасту и начислению.",
    visTitle: "ПЛАНЫ НА БУДУЩЕЕ",
    visAutoAgents: "Автономные Юридические Агенты",
    visAutoAgentsDesc: "AI агенты, способные автономно вести переговоры и готовить документы.",
    visCourtAPI: "Интеграция с Судом",
    visCourtAPIDesc: "Прямая интеграция с E-Sud для отслеживания дел в реальном времени.",
    visBlockchain: "Блокчейн Нотариус",
    visBlockchainDesc: "Неизменная проверка контрактов через Национальный Блокчейн.",
    visAIJudge: "Пилот AI Судьи",
    visAIJudgeDesc: "Предварительная оценка дел для снижения судебной нагрузки.",
    statPlatformImpact: "ПОКАЗАТЕЛИ ПЛАТФОРМЫ",
    statUsers: "Активных пользователей",
    statDocs: "Документов создано",
    statAccuracy: "Юридическая точность",
    statAIAvailability: "Доступность ИИ",
    statLanguages: "Языки",
    statSystemOp: "Система работает",
    footerCopyright: "Lawify Inc. © 2026",
    techTitle: "Надежные Технологии",
    techSecure: "Безопасно и Зашифровано",
    techModel: "Специализированный ИИ",
    techModelSub: "Без галлюцинаций",
    techDatabase: "База Lex.uz",
    libraryTitle: "Библиотека Документов",
    librarySubtitle: "AI Секретарь поможет составить любой документ за минуты.",
    librarySelectPrompt: "Выберите шаблон, чтобы начать.",
    libraryDifficulty: "Сложность",
    libraryComingSoon: "Скоро",
    libraryFooter: "Все шаблоны полностью соответствуют законодательству Республики Узбекистан и одобрены юристами.",
    catCivil: "Гражданское",
    catProperty: "Имущество",
    catFamily: "Семья",
    catBusiness: "Бизнес",
    catAdmin: "Административное",
    tDebtTitle: "Долговая Расписка",
    tDebtDesc: "Оформление займа денег.",
    tRentTitle: "Договор Аренды",
    tRentDesc: "Аренда жилья или офиса.",
    tDivorceTitle: "Заявление на Развод",
    tDivorceDesc: "Официальное заявление в суд.",
    tLaborTitle: "Трудовой Договор",
    tLaborDesc: "Соглашение между работодателем и сотрудником.",
    tPowerTitle: "Доверенность",
    tPowerDesc: "На управление автомобилем или имуществом.",
    tComplaintTitle: "Жалоба",
    tComplaintDesc: "Жалоба на государственные органы.",
    tDebtPrompt: "Я хочу составить долговую расписку. Пожалуйста, задайте мне необходимые вопросы (стороны, сумма, срок), чтобы составить документ юридически грамотно.",
    tRentPrompt: "Я хочу составить договор аренды жилья. Пожалуйста, запросите у меня необходимые данные для составления договора.",
    tDivorcePrompt: "Мне нужно подать заявление на развод. Пожалуйста, спросите меня о деталях брака и детях, чтобы сформировать заявление.",
    tLaborPrompt: "Мне нужно составить трудовой договор по новому ТК РУз. Пожалуйста, уточните условия работы и данные сторон.",
    tPowerPrompt: "Мне нужна доверенность (на авто или имущество). Пожалуйста, узнайте у меня детали, прежде чем составлять текст.",
    tComplaintPrompt: "Я хочу написать жалобу в госорган. Пожалуйста, задайте мне вопросы по ситуации, чтобы текст был обоснованным.",
    diffEasy: "Легко",
    diffMedium: "Средне",
    diffHard: "Сложно",
    topicsTitle: "Общие Юридические Темы",
    topicsSubtitle: "Выберите тему для предварительного заполнения формы",
    historyTitle: "История Дел",
    historySubtitle: "Ваши предыдущие консультации хранятся локально на этом устройстве.",
    historyClear: "Очистить историю",
    historyEmpty: "Истории пока нет. Начните новый чат.",
    historyMessages: "сообщений",
    profileTitle: "Профиль",
    profileSubtitle: "Управление личными данными и настройками",
    profileName: "Имя",
    profileEmail: "Email",
    profileStats: "Статистика",
    profileConsultations: "Консультаций",
    profileSavedDocs: "Сохр. документы",
    profileSave: "Сохранить",
    filterTitle: "Фильтр",
    filterDate: "Дата",
    filterRole: "От кого",
    filterAll: "Все",
    filterUser: "Пользователь",
    filterAI: "AI Юрист",
    filterLast24h: "За 24 часа",
    filterLastWeek: "За неделю",
    filterAllTime: "Все время",
    plansTitle: "Тарифные Планы",
    plansSubtitle: "Выберите подходящий тариф. Можно отменить в любое время.",
    currentPlan: "Текущий план",
    subscribe: "Выбрать",
    featRequestLimit: "запросов / день",
    featUnlimited: "Безлимитные запросы",
    featDocs: "анализ документов",
    featNoDocs: "Без загрузки документов",
    featSpeedNormal: "Стандартная скорость",
    featSpeedFast: "Высокая скорость (Pro)",
    featLive: "Живой голосовой чат",
    featLiveLimit: "мин/день",
    featReasoning: "Глубокий юр. анализ",
    featSupport: "Поддержка клиентов",
    featMobile: "Мобильный доступ",
    featHistory: "Сохранение истории",
    featAds: "Без рекламы",
    featExport: "Экспорт в PDF",
    pFreeName: "Бесплатный",
    pFreePrice: "0",
    pDayName: "Дневной Pro",
    pDayPrice: "15 000",
    pWeekName: "Дневной Pro",
    pWeekPrice: "49 000",
    pMonthName: "Месячный Pro",
    pMonthPrice: "119 000",
    pLawyerName: "Юрист Pro",
    pLawyerPrice: "299 000",
    currency: "сум",
    bestValue: "Выгодно",
    limitReachedTitle: "Дневной лимит исчерпан",
    limitReachedBody: "Вы использовали 5 бесплатных вопросов на сегодня.",
    limitUpgrade: "Смотреть тарифы Pro",
    limitReturn: "Вернуться завтра",
    freeUsage: "Бесплатные запросы:",
    odilbekTitle: "Одилбек AI - Правовой Консультант",
    odilbekSubtitle: "Я объясню советы AI Юриста простым языком. Спрашивайте безлимитно!",
    odilbekWelcome: "Здравствуйте! Я Одилбек (Оксфордский магистр). Совет нашего адвоката показался сложным? Перешлите его мне, я всё объясню простыми словами.",
    askOdilbek: "Спросить Одилбека (Безлимитно)",
    odilbekAction: "Объяснить подробно",
    odilbekPlaceholder: "Спросите у Одилбека что угодно...",
  },
  [Language.EN]: {
    profileLoginPrompt: "Please login to manage your profile and subscription.",
    profileLoginBtn: "Login / Register",
    title: "LAWIFY",
    subtitle: "Uzbekistan Legal Assistant",
    settings: "Settings",
    length: "Answer Length",
    tone: "Tone",
    style: "Output Style",
    clarify: "Clarifying Questions",
    short: "Short",
    medium: "Medium",
    detailed: "Detailed",
    simple: "Simple",
    professional: "Professional",
    bullets: "Bullet points",
    steps: "Step-by-step",
    paragraphs: "Paragraphs",
    docType: "Document Type",
    docGeneral: "General Advice",
    docContract: "Contract",
    docLetter: "Official Letter",
    docApp: "Application",
    perspective: "Perspective",
    persNeutral: "Neutral",
    persConsumer: "Pro-Consumer",
    persBusiness: "Pro-Business",
    inputPlaceholder: "Ask a legal question...",
    disclaimer: "This is informational guidance, not a substitute for a licensed lawyer. For urgent cases consult a lawyer.",
    startLive: "Live Chat",
    stopLive: "End Chat",
    speaking: "Speaking...",
    listening: "Listening...",
    send: "Send",
    uploadImage: "Upload Image",
    uploadDoc: "Upload Document",
    audioPermission: "Microphone permission required",
    thinking: "Thinking...",
    fileSelected: "File selected",
    connectedSources: "Connected: 19 Codes & Lex.uz",
    sourcesTitle: "OFFICIAL SOURCES",
    navDashboard: "Dashboard",
    navChat: "AI Lawyer",
    navOdilbek: "Odilbek (Explainer)",
    navTemplates: "AI Secretary",
    navHistory: "History",
    navTopics: "Topics",
    navProfile: "Profile",
    navPlans: "Pricing",
    upgradeBtn: "Upgrade to Pro",
    dashboardWelcome: "Welcome Back",
    dashboardSubtitle: "How can I assist with your legal needs today?",
    quickChat: "Start Consultation",
    quickChatDesc: "Ask general legal questions",
    quickContracts: "Review Contract",
    quickContractsDesc: "Analyze legal risks in docs",
    quickTemplates: "AI Secretary",
    quickTemplatesDesc: "Draft Documents",
    openApp: "Open App",
    didYouKnowTitle: "Uzbekistan's New Labor Code",
    didYouKnowContent: "The new Labor Code of 2023 introduced significant changes to employee rights, vacation calculations, and remote work regulations.",
    didYouKnowButton: "Learn More",
    didYouKnowTag: "Did you know?",
    quickLinksTitle: "Quick Links",
    qlFamily: "Family Law",
    qlLabor: "Labor Code",
    qlCriminal: "Criminal Code",
    qlBusiness: "Business Law",
    qlHousing: "Housing Law",
    qlAdmin: "Administrative Law",
    qlBank: "Bank & Credit",
    qlHealth: "Healthcare",
    qlEdu: "Education Law",
    qlCustoms: "Customs",
    qlTax: "Taxes",
    qlPension: "Pension",
    qlFamilyPrompt: "I have a question regarding Family Law.",
    qlLaborPrompt: "I need information about the Labor Code.",
    qlCriminalPrompt: "I have a question about the Criminal Code.",
    qlHousingPrompt: "I have a question about Housing Law.",
    qlBusinessPrompt: "I need legal advice for Business.",
    qlAdminPrompt: "Question about Administrative Liability.",
    qlBankPrompt: "Question about bank loans and deposits.",
    qlHealthPrompt: "Question about medical services and patient rights.",
    qlEduPrompt: "Question about education, tuition, and transfers.",
    qlCustomsPrompt: "I need info on customs duties and regulations.",
    qlTaxPrompt: "Question about taxes and benefits.",
    qlPensionPrompt: "Question about retirement age and calculation.",
    visTitle: "FUTURE PLANS",
    visAutoAgents: "Autonomous Legal Agents",
    visAutoAgentsDesc: "AI agents that can negotiate and file documents autonomously.",
    visCourtAPI: "Court API Integration",
    visCourtAPIDesc: "Direct integration with E-Sud for real-time case tracking.",
    visBlockchain: "Blockchain Notary",
    visBlockchainDesc: "Immutable contract verification via National Blockchain.",
    visAIJudge: "AI Judge Assistance Pilot",
    visAIJudgeDesc: "Preliminary case assessment to reduce judicial load.",
    statPlatformImpact: "PLATFORM IMPACT",
    statUsers: "Active Users",
    statDocs: "Documents Generated",
    statAccuracy: "Legal Accuracy",
    statAIAvailability: "AI Availability",
    statLanguages: "Languages",
    statSystemOp: "System Operational",
    footerCopyright: "Lawify Inc. © 2026",
    techTitle: "Trusted Technology",
    techSecure: "Secure & Encrypted",
    techModel: "Specialized Legal AI",
    techModelSub: "No Hallucinations",
    techDatabase: "Lex.uz Database",
    libraryTitle: "Legal Document Library",
    librarySubtitle: "Draft any document in minutes with AI Secretary.",
    librarySelectPrompt: "Select a template to start drafting.",
    libraryDifficulty: "Difficulty",
    libraryComingSoon: "Coming Soon", 
    libraryFooter: "All templates are fully compliant with the legislation of the Republic of Uzbekistan and approved by lawyers.",
    catCivil: "Civil",
    catProperty: "Property",
    catFamily: "Family",
    catBusiness: "Business",
    catAdmin: "Administrative",
    tDebtTitle: "Debt Receipt",
    tDebtDesc: "Formalize lending or borrowing money.",
    tRentTitle: "Rental Agreement",
    tRentDesc: "For residential or commercial property leasing.",
    tDivorceTitle: "Divorce Application",
    tDivorceDesc: "Formal application for court submission.",
    tLaborTitle: "Labor Contract",
    tLaborDesc: "Agreement between employer and employee.",
    tPowerTitle: "Power of Attorney",
    tPowerDesc: "For managing vehicle or property.",
    tComplaintTitle: "Complaint Letter",
    tComplaintDesc: "Complaint against government bodies.",
    tDebtPrompt: "I want to draft a Debt Receipt. Please ask me for the specific details (lender, borrower, amount, date) needed to make it legally valid before drafting.",
    tRentPrompt: "I want to create a Rental Agreement. Please interview me about the property, rent amount, and terms before generating the document.",
    tDivorcePrompt: "I need to write a Divorce Application for the court. Please ask me for the necessary details about marriage and children first.",
    tLaborPrompt: "I need to draft a Labor Contract under the new Labor Code. Please ask me about the job conditions and parties involved.",
    tPowerPrompt: "I need a Power of Attorney (for car or property). Please ask me for the specific details required by law.",
    tComplaintPrompt: "I want to file a formal Complaint against a government body. Please ask me clarifying questions about the incident first.",
    diffEasy: "Easy",
    diffMedium: "Medium",
    diffHard: "Hard",
    topicsTitle: "Common Legal Topics",
    topicsSubtitle: "Select a topic to pre-fill the inquiry",
    historyTitle: "Case History",
    historySubtitle: "Your previous consultations are stored locally on this device.",
    historyClear: "Clear History",
    historyEmpty: "No history yet. Start a new chat.",
    historyMessages: "messages",
    profileTitle: "User Profile",
    profileSubtitle: "Manage your personal information and preferences",
    profileName: "Name",
    profileEmail: "Email",
    profileStats: "Statistics",
    profileConsultations: "Consultations",
    profileSavedDocs: "Saved Docs",
    profileSave: "Save Changes",
    filterTitle: "Filter Chat",
    filterDate: "Date Range",
    filterRole: "Sender",
    filterAll: "All",
    filterUser: "User Only",
    filterAI: "AI Lawyer Only",
    filterLast24h: "Last 24 Hours",
    filterLastWeek: "Last Week",
    filterAllTime: "All Time",
    plansTitle: "Pricing Plans",
    plansSubtitle: "Select the plan that fits your needs. Cancel anytime.",
    currentPlan: "Current Plan",
    subscribe: "Subscribe",
    featRequestLimit: "requests / day",
    featUnlimited: "Unlimited requests",
    featDocs: "document analyses",
    featNoDocs: "No document uploads",
    featSpeedNormal: "Standard Speed",
    featSpeedFast: "Pro Speed",
    featLive: "Live Voice Chat",
    featLiveLimit: "min/day",
    featReasoning: "Deep Legal Reasoning",
    featSupport: "Customer Support",
    featMobile: "Mobile Access",
    featHistory: "History Retention",
    featAds: "Ad-free Experience",
    featExport: "PDF Export",
    pFreeName: "Free",
    pFreePrice: "0",
    pDayName: "Day Pro",
    pDayPrice: "15,000",
    pWeekName: "Week Pro",
    pWeekPrice: "49,000",
    pMonthName: "Month Pro",
    pMonthPrice: "119,000",
    pLawyerName: "Lawyer Pro",
    pLawyerPrice: "299,000",
    currency: "UZS",
    bestValue: "Best Value",
    limitReachedTitle: "Daily Limit Reached",
    limitReachedBody: "You've used your 5 free questions for today.",
    limitUpgrade: "View Pro Plans",
    limitReturn: "Come back tomorrow",
    freeUsage: "Free usage:",
    odilbekTitle: "Odilbek AI - Legal Explainer",
    odilbekSubtitle: "I explain AI Lawyer's advice in simple terms. Ask me anything, unlimited!",
    odilbekWelcome: "Hello! I'm Odilbek (Oxford Master Graduate). Did the Lawyer's advice sound too complicated? Send it over, and I'll break it down for you.",
    askOdilbek: "Ask Odilbek (Unlimited)",
    odilbekAction: "Explain this",
    odilbekPlaceholder: "Ask Odilbek anything...",
  }
};